import assert from 'node:assert/strict';
import test from 'node:test';
import { POST, GET, FILE_POST, FILE_GET, TestDatabase, state, signIn } from './helpers/platform-api.mjs';
const origin = 'https://materials.test', period = '2026-2027';
function fixture(area = 'complexive') {
  const db = new TestDatabase(), objects = new Map(); state.env.DB = db; state.env.BUCKET = { put: async (key, bytes, options) => objects.set(key, { bytes, ...options }), head: async key => objects.get(key), get: async key => { const row = objects.get(key); return row && { body: row.bytes, httpEtag: 'test', writeHttpMetadata: h => h.set('content-type', row.httpMetadata.contentType) }; } };
  for (const who of ['teacher', 'student']) db.sql.prepare('INSERT INTO profiles(id,auth_id,email,full_name,role,status,group_id) VALUES(?,?,?,?,?,?,?)').run(who, `auth-${who}`, `${who === 'teacher' ? 'profesor' : who}@example.test`, who, who === 'teacher' ? 'admin' : 'student', 'active', who === 'teacher' ? null : 'group');
  db.add('p', 'period', period, 'published', { current: true }); db.add('sim-ef-pilot', 'simulator', 'Sentinel', 'archived', {}); db.add('group', 'group', 'Grupo', 'active', { plan: 'Gold', planStatus: 'active', endsAt: '2099-01-01' });
  db.add('material', 'resource', 'Material original', 'published', { area, period, subject: 'Ciencias', topic: 'Tema 1', topicId: 'tema-1', plan: 'Bronce', materialType: 'Documento', externalUrl: 'https://example.edu/original', additionalCategory: 'planning' });
  db.add('q', 'question', 'Pregunta', 'approved', { area, period, subject: 'Ciencias', sourceResourceId: 'material', prompt: 'Pregunta original' }); db.add('attempt', 'attempt', 'Intento previo', 'finalized', { score: 20, questions: [{ prompt: 'Pregunta original' }] }, 'group', 'student'); signIn(); return { db, objects };
}
async function post(body, status = 200) { const response = await POST(new Request(`${origin}/api/platform`, { method: 'POST', headers: { origin, 'sec-fetch-site': 'same-origin', 'content-type': 'application/json' }, body: JSON.stringify(body) })); const result = await response.json(); assert.equal(response.status, status, JSON.stringify(result)); return result; }
const body = db => { const row = db.record('material'); return { action: 'save_academic_material', id: row.id, revision: row.data.materialRevision || row.updated_at, title: 'Material editado', data: { description: 'Descripción revisada', plan: 'Plata' } }; };
async function upload() { const response = await FILE_POST(new Request(`${origin}/api/files?kind=material&fileName=material.pdf`, { method: 'POST', headers: { origin, 'sec-fetch-site': 'same-origin' }, body: new TextEncoder().encode('%PDF-1.4\nPrueba\n%%EOF') })); assert.equal(response.status, 200); return response.json(); }
test('academic material metadata edits preserve subject, topic, reference and attempts in both areas', async () => {
  for (const area of ['complexive', 'final_degree']) { const f = fixture(area); try { const attempt = f.db.record('attempt'); await post({ ...body(f.db), data: { plan: 'Plata', description: 'Editado', area: 'resources', subject: 'Otra', topicId: 'otro', role: 'admin' } }); const row = f.db.record('material'); assert.equal(row.status, 'draft'); assert.equal(row.data.area, area); assert.equal(row.data.subject, 'Ciencias'); assert.equal(row.data.topicId, 'tema-1'); assert.equal(row.data.additionalCategory, 'planning'); assert.equal(f.db.record('q').status, 'approved'); assert.deepEqual(f.db.record('attempt'), attempt); } finally { f.db.sql.close(); } }
});
test('replacing academic content preserves a version and atomically returns only its current questions to review', async () => {
  const f = fixture(); try { const file = await upload(), attempt = f.db.record('attempt'); f.db.add('historic', 'question', 'Historia', 'approved', { area: 'complexive', period: '2025-2026', sourceResourceId: 'material' }); const result = await post({ ...body(f.db), replaceContent: true, data: { ...file, fileKey: file.key, materialType: 'Documento', plan: 'Bronce' } }); const row = f.db.record('material'); assert.equal(result.questionsToReview, 1); assert.equal(row.data.materialVersions.length, 1); assert.equal(row.data.materialVersions[0].externalUrl, 'https://example.edu/original'); assert.equal(row.data.fileKey, file.key); assert.equal(f.db.record('q').status, 'pending'); assert.equal(f.db.record('historic').status, 'approved'); assert.deepEqual(f.db.record('attempt'), attempt); assert.equal(f.objects.size, 1);
    signIn('student'); const response = await FILE_GET(new Request(`${origin}/api/files?key=${encodeURIComponent(file.key)}`)); assert.equal(response.status, 403); signIn(); await post({ action: 'update_status', id: 'material', status: 'published' }); signIn('student'); const catalog = await (await GET()).json(); assert.ok(catalog.records.some(r => r.id === 'material')); assert.equal('materialVersions' in catalog.records.find(r => r.id === 'material').data, false);
  } finally { f.db.sql.close(); }
});
test('academic edits reject students, historical and archived material and stale forms', async () => {
  const f = fixture(); try { const original = f.db.record('material'), input = body(f.db); signIn('student'); await post(input, 403); signIn(); await post({ ...input, revision: 'stale' }, 409); assert.deepEqual(f.db.record('material'), original); await post(input); await post(input, 409); f.db.sql.prepare("UPDATE records SET status='archived' WHERE id='material'").run(); await post(body(f.db), 409); f.db.sql.prepare("UPDATE records SET status='published',data_json=json_set(data_json,'$.period','2025-2026') WHERE id='material'").run(); await post(body(f.db), 409); } finally { f.db.sql.close(); }
});
test('invalid replacement, unowned files and invalid plans never mutate academic data', async () => {
  const f = fixture(); try { const original = f.db.record('material'); for (const data of [{ plan: ['Gold'] }, { plan: 'admin' }]) await post({ ...body(f.db), data }, 400); for (const data of [{ materialType: 'Audio', plan: 'Bronce' }, { materialType: 'Documento', plan: 'Bronce', fileKey: 'materials/shared/fake.pdf' }, { materialType: 'Video', plan: 'Bronce', externalUrl: 'javascript:alert(1)' }]) await post({ ...body(f.db), replaceContent: true, data }, 400); assert.deepEqual(f.db.record('material'), original); assert.equal(f.db.record('q').status, 'approved'); } finally { f.db.sql.close(); }
});
test('concurrent material edits cannot invalidate questions or overwrite the reviewed file', async () => {
  const f = fixture(); try { const file = await upload(), batch = f.db.batch.bind(f.db); f.db.batch = async statements => { f.db.sql.prepare("UPDATE records SET title='Cambio concurrente' WHERE id='material'").run(); return batch(statements); }; await post({ ...body(f.db), replaceContent: true, data: { fileKey: file.key, materialType: 'Documento', plan: 'Bronce' } }, 409); assert.equal(f.db.record('q').status, 'approved'); assert.equal(f.db.record('material').title, 'Cambio concurrente'); assert.equal(f.db.record('material').data.materialVersions, undefined); } finally { f.db.sql.close(); }
});
