import assert from 'node:assert/strict';
import test from 'node:test';
import { groupNavigation } from "../lib/navigation-groups.ts";
import { readNavigation, readSelection, writeSelection } from '../lib/navigation.ts';
test('navigation restores valid workspace destinations without granting administrative mode',()=>{assert.deepEqual(readNavigation('#admin/final/questions',true),{mode:'admin',section:'final',step:'questions'});assert.deepEqual(readNavigation('#admin/plans',false),{mode:'student',section:'home',step:'materials'});assert.equal(readNavigation('#student/resources',true).section,'resources');assert.equal(readNavigation('#admin/unknown',true).section,'dashboard');});
test('academic selections are isolated by user/area/period and validate corrupted storage',()=>{const map=new Map<string,string>(),storage={getItem:(key:string)=>map.get(key)||null,setItem:(key:string,value:string)=>{map.set(key,value);}};writeSelection(storage,'u1:2026:complexive:subject','Ciencias');assert.equal(readSelection(storage,'u1:2026:complexive:subject',''), 'Ciencias');assert.equal(readSelection(storage,'u2:2026:complexive:subject',''), '');assert.equal(readSelection(storage,'u1:2027:complexive:subject',''), '');writeSelection(storage,'step','invalid');assert.equal(readSelection(storage,'step','materials',['materials','questions']),'materials');map.set('tutosebas:selection:topic','{');assert.equal(readSelection(storage,'topic',''),'');});
test('blocked or full browser storage never prevents navigation',()=>{const storage={getItem(){throw new Error('blocked');},setItem(){throw new Error('quota');}};assert.equal(readSelection(storage,'scope','Ciencias'),'Ciencias');assert.doesNotThrow(()=>writeSelection(storage,'scope','Ciencias'));});

test('grouped menus retain each original destination exactly once in both roles',()=>{for(const ids of [['dashboard','students','payments','plans','periods','final','complexive','reviews','resources','notices','reports','settings'],['home','final','complexive','work','resources','deliveries','group','plan','notices','account']]){const groups=groupNavigation(ids.map(id=>[id] as const)),actual=groups.flatMap(group=>group.items.map(item=>item[0]));assert.deepEqual([...actual].sort(),[...ids].sort());assert.equal(new Set(actual).size,ids.length);assert.ok(groups.length>1);} });
