import assert from 'node:assert/strict';
import test from 'node:test';
import {POST,GET,TestDatabase,state,signIn} from './helpers/platform-api.mjs';
const origin='https://notices.test';
function fixture(){
 const db=new TestDatabase();state.env.DB=db;
 for(const who of ['teacher','student','other','peer'])db.sql.prepare('INSERT INTO profiles(id,auth_id,email,full_name,role,status,group_id) VALUES(?,?,?,?,?,?,?)').run(who,`auth-${who}`,`${who==='teacher'?'profesor':who}@example.test`,who,who==='teacher'?'admin':'student','active',who==='teacher'?null:who==='other'?'b':'a');
 db.add('period-current','period','2026-2027','published',{current:true});db.add('sim-ef-pilot','simulator','Sentinel','archived',{});
 for(const g of ['a','b'])db.add(g,'group',g,'active',{plan:'Gold',planStatus:'active',endsAt:'2099-01-01'});
 db.add('n','notice','Aviso privado','published',{body:'Mensaje original',noticeRevision:'r1',readBy:['student']},'a');
 signIn();return db;
}
async function post(body,status=200){const r=await POST(new Request(`${origin}/api/platform`,{method:'POST',headers:{origin,'sec-fetch-site':'same-origin','content-type':'application/json'},body:JSON.stringify(body)}));const j=await r.json();assert.equal(r.status,status,JSON.stringify(j));return j;}
const save=(db,status='published',data={body:'Mensaje corregido',groupId:'a'})=>{const r=db.record('n');return{action:'save_notice',id:'n',revision:r.data.noticeRevision||r.updated_at,title:'Aviso corregido',status,data};};
const change=(db,status)=>{const r=db.record('n');return{action:'set_notice_status',id:'n',revision:r.data.noticeRevision||r.updated_at,status};};
test('notice corrections retain prior readers privately and reach only new recipients as unread',async()=>{const db=fixture();try{await post(save(db,'published',{body:'Mensaje de otro grupo',groupId:'b',readBy:['other'],noticeVersions:[{body:'Falso'}]}));const r=db.record('n');assert.equal(r.data.noticeVersions.length,1);assert.deepEqual(r.data.noticeVersions[0].readBy,['student']);assert.equal(r.data.noticeVersions[0].body,'Mensaje original');assert.deepEqual(r.data.readBy,[]);signIn('student');assert.ok(!(await(await GET()).json()).records.some(r=>r.id==='n'));signIn('other');const visible=(await(await GET()).json()).records.find(r=>r.id==='n');assert.equal(visible.data.read,false);assert.equal(visible.data.noticeVersions,undefined);assert.equal(visible.data.readBy,undefined);assert.equal(visible.data.updatedBy,undefined);await post({action:'mark_notice',id:'n',revision:r.data.noticeRevision});assert.deepEqual(db.record('n').data.readBy,['other']);}finally{db.sql.close();}});
test('archive and restore preserve messages and require explicit publication',async()=>{const db=fixture();try{await post(change(db,'archived'));assert.equal(db.record('n').data.noticeVersions.length,1);signIn('student');assert.ok(!(await(await GET()).json()).records.some(r=>r.id==='n'));await post({action:'mark_notice',id:'n'},403);signIn();await post(change(db,'draft'));assert.equal(db.record('n').status,'draft');signIn('student');assert.ok(!(await(await GET()).json()).records.some(r=>r.id==='n'));signIn();await post(change(db,'published'));assert.deepEqual(db.record('n').data.readBy,[]);assert.equal(db.record('n').data.noticeVersions.length,3);db.add('empty','notice','Aviso antiguo vacío','published',{body:''});const empty=db.record('empty');await post({action:'set_notice_status',id:'empty',revision:empty.updated_at,status:'archived'});assert.equal(db.record('empty').status,'archived');await post({action:'set_notice_status',id:'empty',revision:db.record('empty').data.noticeRevision,status:'published'},400);}finally{db.sql.close();}});
test('notice creation and edits reject spoofing, invalid fields, stale revisions and unauthorized roles',async()=>{const db=fixture();try{signIn('student');await post(save(db),403);signIn();const original=db.record('n');for(const input of [{...save(db),title:'x'.repeat(181)},{...save(db),data:{body:' '}},{...save(db),data:{body:'x'.repeat(4001)}},{...save(db),data:{body:'Mensaje',groupId:'missing'}},{...save(db),revision:'old'},{...save(db),status:'approved'}])await post(input,input.revision==='old'?409:400);assert.deepEqual(db.record('n'),original);await post({action:'update_status',id:'n',status:'archived'},400);await post({action:'create_record',kind:'notice',title:'Nuevo',status:'published',data:{body:''}},400);const created=await post({action:'create_record',kind:'notice',title:'Nuevo',status:'published',data:{body:'Válido',groupId:'a',readBy:['student'],noticeVersions:[1],noticeRevision:'forged'}});assert.deepEqual(db.record(created.id).data.readBy,[]);assert.equal(db.record(created.id).data.noticeVersions,undefined);assert.notEqual(db.record(created.id).data.noticeRevision,'forged');}finally{db.sql.close();}});
test('concurrent readers merge without dropping earlier reads or leaking the reader list',async()=>{const db=fixture();try{db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.readBy',json('[]')) WHERE id='n'").run();const prepare=db.prepare.bind(db);let fired=false;db.prepare=q=>{const s=prepare(q),bind=s.bind;s.bind=(...args)=>{const b=bind(...args);if(q.startsWith('UPDATE records SET data_json=json_set')){const run=b.run;b.run=async()=>{if(!fired){fired=true;db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.readBy',json('[\"peer\"]')) WHERE id='n'").run();}return run();};}return b;};return s;};signIn('student');await post({action:'mark_notice',id:'n',revision:'r1'});assert.deepEqual(db.record('n').data.readBy,['peer','student']);await post({action:'mark_notice',id:'n',revision:'r1'});assert.equal(db.record('n').data.readBy.length,2);const publicRow=(await(await GET()).json()).records.find(r=>r.id==='n');assert.equal(publicRow.data.read,true);assert.equal(publicRow.data.readBy,undefined);}finally{db.sql.close();}});
test('an old read request cannot overwrite an edited notice or acknowledge the new version',async()=>{const db=fixture();try{db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.readBy',json('[]')) WHERE id='n'").run();const prepare=db.prepare.bind(db);db.prepare=q=>{const s=prepare(q),bind=s.bind;s.bind=(...args)=>{const b=bind(...args);if(q.startsWith('UPDATE records SET data_json=json_set')){const run=b.run;b.run=async()=>{db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.body','Nuevo','$.noticeRevision','r2') WHERE id='n'").run();return run();};}return b;};return s;};signIn('student');await post({action:'mark_notice',id:'n',revision:'r1'},409);assert.equal(db.record('n').data.body,'Nuevo');assert.deepEqual(db.record('n').data.readBy,[]);}finally{db.sql.close();}});
test('concurrent saves and a full version history preserve the latest data',async()=>{const db=fixture();try{const input=save(db),prepare=db.prepare.bind(db);db.prepare=q=>{const s=prepare(q),bind=s.bind;s.bind=(...args)=>{const b=bind(...args);if(q.startsWith('UPDATE records SET title=?')){const run=b.run;b.run=async()=>{db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.noticeRevision','winner','$.body','Ganador') WHERE id='n'").run();return run();};}return b;};return s;};await post(input,409);assert.equal(db.record('n').data.body,'Ganador');assert.equal(db.record('n').data.noticeVersions,undefined);db.prepare=prepare;db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.noticeVersions',json(?)) WHERE id='n'").run(JSON.stringify(Array.from({length:50},(_,id)=>({id,body:'Historia'}))));await post(save(db),409);assert.equal(db.record('n').data.noticeVersions.length,50);}finally{db.sql.close();}});
