import assert from 'node:assert/strict';
import test from 'node:test';
import { POST, GET, TestDatabase, state, signIn } from './helpers/platform-api.mjs';
const origin='https://payments.test';
function fixture(){const db=new TestDatabase();state.env.DB=db;for(const who of ['teacher','student','other'])db.sql.prepare('INSERT INTO profiles(id,auth_id,email,full_name,role,status,group_id,member_role) VALUES(?,?,?,?,?,?,?,?)').run(who,`auth-${who}`,`${who==='teacher'?'profesor':who}@example.test`,who,who==='teacher'?'admin':'student','active',who==='teacher'?null:'g',who==='student'?'coordinator':'member');db.add('period-current','period','2026-2027','published',{current:true});db.add('sim-ef-pilot','simulator','Sentinel','archived',{});db.add('g','group','Grupo','active',{plan:'Gold',planStatus:'active',endsAt:new Date(Date.now()+10*86400000).toISOString(),accessPolicyVersion:1,featureOverrides:{'resources.apa':'deny'}});db.add('pay','payment','Pago','pending',{plan:'Gold',amount:30,reviewNote:''},'g','student');signIn();return db;}
async function post(body,status=200){const r=await POST(new Request(`${origin}/api/platform`,{method:'POST',headers:{origin,'sec-fetch-site':'same-origin','content-type':'application/json'},body:JSON.stringify(body)}));const j=await r.json();assert.equal(r.status,status,JSON.stringify(j));return j;}
test('rejection requires a bounded reason and preserves group access/dates',async()=>{const db=fixture();try{const group=db.record('g'),payment=db.record('pay');await post({action:'review_payment',id:'pay',status:'rejected'},400);await post({action:'review_payment',id:'pay',status:'rejected',reviewNote:'x'.repeat(1001)},400);assert.deepEqual(db.record('pay'),payment);await post({action:'review_payment',id:'pay',status:'rejected',reviewNote:'  El comprobante no es legible.  '});assert.equal(db.record('pay').data.reviewNote,'El comprobante no es legible.');assert.equal(db.record('pay').data.reviewedBy,'teacher');assert.deepEqual(db.record('g'),group);const reviewed=db.record('pay');await post({action:'review_payment',id:'pay',status:'rejected',reviewNote:'Otro motivo'});assert.deepEqual(db.record('pay'),reviewed);await post({action:'review_payment',id:'pay',status:'approved'},409);}finally{db.sql.close();}});
test('only teachers review and only the coordinator sees the private payment and reason',async()=>{const db=fixture();try{signIn('student');await post({action:'review_payment',id:'pay',status:'rejected',reviewNote:'No'},403);signIn();await post({action:'review_payment',id:'pay',status:'rejected',reviewNote:'Valor incorrecto'});signIn('student');const own=await(await GET()).json();assert.equal(own.records.find(row=>row.id==='pay').data.reviewNote,'Valor incorrecto');signIn('other');const member=await(await GET()).json();assert.equal(member.records.some(row=>row.id==='pay'),false);}finally{db.sql.close();}});
test('approval extends unused time once while preserving manual access exceptions',async()=>{const db=fixture();try{const original=db.record('g').data;await post({action:'review_payment',id:'pay',status:'approved',reviewNote:'Verificado'});const approved=db.record('g');assert.equal(Date.parse(approved.data.endsAt)-Date.parse(original.endsAt),30*86400000);assert.deepEqual(approved.data.featureOverrides,original.featureOverrides);await post({action:'review_payment',id:'pay',status:'approved'});assert.deepEqual(db.record('g'),approved);await post({action:'review_payment',id:'missing',status:'approved'},404);}finally{db.sql.close();}});
