import assert from 'node:assert/strict';
import test from 'node:test';
import { POST, GET, TestDatabase, state, signIn } from './helpers/platform-api.mjs';
const origin='https://periods.test', before='2026-2027', after='2027-2028';
function fixture() { const db=new TestDatabase();state.env.DB=db;for(const who of ['teacher','student'])db.sql.prepare('INSERT INTO profiles(id,auth_id,email,full_name,role,status,group_id) VALUES(?,?,?,?,?,?,?)').run(who,`auth-${who}`,`${who==='teacher'?'profesor':who}@example.test`,who,who==='teacher'?'admin':'student','active',who==='teacher'?null:'g');db.add('period-current','period',before,'published',{current:true});db.add('sim-ef-pilot','simulator','Sentinel','archived',{});db.add('g','group','Grupo','active',{plan:'Gold',planStatus:'active',endsAt:'2099-01-01',accessPolicyVersion:1});db.add('old-subject','subject','Ciencias','published',{area:'complexive',period:before});db.add('old-resource','resource','Video','published',{area:'complexive',subject:'Ciencias',topic:'Tema 1',period:before,materialType:'Video',externalUrl:'https://example.edu'});db.add('history','attempt','Intento','finalized',{period:before,score:19},'g','student');signIn();return db; }
async function post(body,status=200){const r=await POST(new Request(`${origin}/api/platform`,{method:'POST',headers:{origin,'sec-fetch-site':'same-origin','content-type':'application/json'},body:JSON.stringify(body)}));const j=await r.json();assert.equal(r.status,status,JSON.stringify(j));return j;}
const activation=(db,id)=>{const r=db.sql.prepare("SELECT * FROM records WHERE kind='period' AND json_extract(data_json,'$.current')=1").get();const d=r&&JSON.parse(r.data_json);return{action:'activate_period',id,currentId:r?.id||'',revision:d?.selectionRevision||r?.updated_at||''};};
test('period creation validates years, requires a teacher, ignores forged activation and rejects duplicates',async()=>{const db=fixture();try{signIn('student');await post({action:'create_period',title:after},403);signIn();await post({action:'create_period',title:'2027-2030'},400);await post({action:'create_period',title:after,note:'x'.repeat(4001)},400);const result=await post({action:'create_record',kind:'period',title:after,data:{current:true,note:'Preparación'}});assert.equal(db.record(result.id).data.current,false);assert.equal(db.record(result.id).status,'draft');await post({action:'create_period',title:after},409);await post({action:'update_status',id:result.id,status:'published'},400);}finally{db.sql.close();}});
test('activation preserves academic history and limits student content to the selected period',async()=>{const db=fixture();try{const history=db.record('history'),resource=db.record('old-resource'),subject=db.record('old-subject');const r=await post({action:'create_period',title:after});await post(activation(db,r.id));assert.equal(db.record('period-current').data.current,false);assert.equal(db.record(r.id).data.current,true);assert.deepEqual(db.record('history'),history);assert.deepEqual(db.record('old-resource'),resource);assert.deepEqual(db.record('old-subject'),subject);assert.equal(db.sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='period' AND json_extract(data_json,'$.current')=1").get().n,1);signIn('student');const list=await (await GET()).json();assert.equal(list.activePeriod,after);assert.equal(list.records.some(row=>row.id==='old-resource'),false);assert.equal(list.records.some(row=>row.id==='history'),true);await post(activation(db,'period-current'),403);}finally{db.sql.close();}});
test('subject creation/removal and question references cannot affect another period',async()=>{const db=fixture();try{const old=db.record('old-resource'),subject=db.record('old-subject');const r=await post({action:'create_period',title:after});await post(activation(db,r.id));await post({action:'create_record',kind:'subject',title:'Ciencias',data:{area:'complexive',period:before}},409);const created=await post({action:'create_record',kind:'subject',title:'Ciencias',data:{area:'complexive',period:after}});const q={action:'create_record',kind:'question',title:'Pregunta',data:{area:'complexive',period:after,subject:'Ciencias',topic:'Tema 1',prompt:'¿Qué opción?',format:'Selección directa',options:['Uno','Dos','Tres','Cuatro'],correctIndex:0,explanation:'Explicación',source:'Sección 1'}};await post({...q,data:{...q.data,sourceResourceId:'old-resource'}},400);const question=await post(q);await post({action:'remove_subject',area:'complexive',subject:'Ciencias',period:before},409);await post({action:'remove_subject',area:'complexive',subject:'Ciencias',period:after});assert.equal(db.record(created.id).status,'archived');assert.equal(db.record(question.id).status,'archived');assert.deepEqual(db.record('old-resource'),old);assert.deepEqual(db.record('old-subject'),subject);}finally{db.sql.close();}});
test('stale and concurrent activation cannot leave two active periods or clear the winner',async()=>{const db=fixture();try{const r=await post({action:'create_period',title:after}),input=activation(db,r.id);const batch=db.batch.bind(db);db.batch=async statements=>{if(statements[0].query.includes("status='published'"))db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.selectionRevision','concurrent') WHERE id='period-current'").run();return batch(statements);};await post(input,409);assert.equal(db.record('period-current').data.current,true);assert.equal(db.record(r.id).data.current,false);db.batch=batch;await post(activation(db,r.id));await post(input,409);assert.equal(db.record(r.id).data.current,true);await post(activation(db,'missing'),404);}finally{db.sql.close();}});
