import assert from 'node:assert/strict';
import test from 'node:test';
import { POST, TestDatabase, state, signIn } from './helpers/platform-api.mjs';
import { studentRevision } from '../lib/students.ts';
function fixture() { const db = new TestDatabase(); state.env.DB = db; for (const who of ['teacher', 'student', 'other']) db.sql.prepare('INSERT INTO profiles(id,auth_id,email,full_name,role,status,group_id,member_role) VALUES(?,?,?,?,?,?,?,?)').run(who, `auth-${who}`, `${who === 'teacher' ? 'profesor' : who}@example.test`, who, who === 'teacher' ? 'admin' : 'student', 'active', who === 'teacher' ? null : 'g1', 'member'); db.add('g1','group','Grupo 1','active',{});db.add('g2','group','Grupo 2','active',{});db.add('p','period','2026-2027','published',{current:true});db.add('sim-ef-pilot','simulator','Sentinel','archived',{});signIn();return db; }
const profile = (db, id = 'student') => db.sql.prepare('SELECT * FROM profiles WHERE id=?').get(id);
const input = db => ({ action:'edit_student',id:'student',revision:studentRevision(profile(db)),fullName:'Nombre corregido',identifierLast4:'1234',groupId:'g2',memberRole:'member' });
async function post(body, expected = 200) { const origin='https://students.test'; const response=await POST(new Request(`${origin}/api/platform`,{method:'POST',headers:{origin,'sec-fetch-site':'same-origin','content-type':'application/json'},body:JSON.stringify(body)}));const result=await response.json();assert.equal(response.status,expected,JSON.stringify(result));return result; }
test('student editing preserves exact identity, status and historical records',async()=>{const db=fixture();try{db.add('history','attempt','Intento','finalized',{score:20},'g1','student');const original=profile(db),history=db.record('history');await post({...input(db),email:'hijack@example.test',auth_id:'other',role:'admin',status:'active'});const row=profile(db);assert.equal(row.full_name,'Nombre corregido');assert.equal(row.group_id,'g2');assert.equal(row.identifier_last4,'1234');for(const field of ['email','auth_id','status','role'])assert.equal(row[field],original[field]);assert.deepEqual(db.record('history'),history);}finally{db.sql.close();}});
test('only teachers edit student profiles and stale/invalid forms make no changes',async()=>{const db=fixture();try{const original=profile(db);signIn('student');await post(input(db),403);signIn();await post({...input(db),id:'teacher'},404);await post({...input(db),revision:'stale'},409);await post({...input(db),identifierLast4:'12'},400);await post({...input(db),memberRole:'admin'},400);await post({...input(db),groupId:'',memberRole:'coordinator'},400);await post({...input(db),groupId:'missing'},409);assert.deepEqual(profile(db),original);await post(input(db));await post({...input(db),revision:studentRevision(original)},409);}finally{db.sql.close();}});
test('group limits and coordinator uniqueness are enforced atomically during edits',async()=>{const db=fixture();try{db.sql.prepare("UPDATE profiles SET member_role='coordinator' WHERE id='other'").run();await post({...input(db),groupId:'g1',memberRole:'coordinator'},409);await post({...input(db),memberRole:'coordinator'});assert.equal(profile(db).member_role,'coordinator');await post({...input(db),groupId:'',memberRole:'member'});assert.equal(profile(db).group_id,null);for(let i=0;i<3;i++)db.sql.prepare("INSERT INTO profiles(id,email,full_name,role,status,group_id,member_role) VALUES(?,?,?,'student','invited','g2','member')").run(`new${i}`,`new${i}@example.test`,'Alumno');await post(input(db),409);assert.equal(profile(db).group_id,null);}finally{db.sql.close();}});
