import assert from 'node:assert/strict';
import test from 'node:test';
import { POST, GET, FILE_POST, FILE_GET, TestDatabase, state, signIn } from './helpers/platform-api.mjs';
const origin='https://subjects.test',period='2026-2027';
function fixture(area='complexive'){
 const db=new TestDatabase(),objects=new Map();state.env.DB=db;state.env.BUCKET={put:async(key,bytes,options)=>objects.set(key,{bytes,...options}),head:async key=>objects.get(key),get:async key=>{const o=objects.get(key);return o&&{body:o.bytes,httpEtag:'test',writeHttpMetadata:h=>h.set('content-type',o.httpMetadata.contentType)};}};
 for(const who of ['teacher','student'])db.sql.prepare('INSERT INTO profiles(id,auth_id,email,full_name,role,status,group_id) VALUES(?,?,?,?,?,?,?)').run(who,`auth-${who}`,`${who==='teacher'?'profesor':who}@example.test`,who,who==='teacher'?'admin':'student','active',who==='teacher'?null:'g');
 db.add('period-current','period',period,'published',{current:true});db.add('sim-ef-pilot','simulator','Sentinel','archived',{});db.add('g','group','Grupo','active',{plan:'Gold',planStatus:'active',endsAt:'2099-01-01',accessPolicyVersion:1});
 const scope={area,period,subject:'Ciencias'};db.add('s','subject','Ciencias','published',{area,period});
 db.add('topic','topic','Tema 1','published',{...scope,number:1});
 db.add('resource','resource','Audio','published',{...scope,topic:'Tema 1',materialType:'Documento',plan:'Bronce'});
 db.add('q','question','Pregunta','approved',{...scope,topic:'Tema 1',format:'Selección directa',options:['A','B','C','D'],correctIndex:0});
 db.add('block','question_block','Bloque','approved',{...scope,topic:'Tema 1'});
 db.add('sim','simulator','Simulador de materia','published',{...scope,mode:'subject',count:5});
 db.add('final','simulator','Examen final','published',{area,period,mode:'final',subject:'General',selectionMode:'subjects',count:10,distribution:[{subject:'Ciencias',count:5},{subject:'Otra',count:5}]});
 db.add('final-block','simulator','Examen bloques','published',{area,period,mode:'final',subject:'General',selectionMode:'blocks',count:4,blockDistribution:[{blockId:'block',subject:'Ciencias',count:4}]});
 db.add('old','resource','Histórico','published',{...scope,period:'2025-2026'});
 db.add('retired','resource','Archivo previo','archived',scope);
 db.add('attempt','attempt','Resultado','finalized',{period,score:17,questions:[{id:'q',correctIndex:0}]},'g','student');signIn();return{db,objects,area};
}
async function post(body,status=200){const r=await POST(new Request(`${origin}/api/platform`,{method:'POST',headers:{origin,'sec-fetch-site':'same-origin','content-type':'application/json'},body:JSON.stringify(body)}));const j=await r.json();assert.equal(r.status,status,JSON.stringify(j));return j;}
const remove=f=>post({action:'remove_subject',area:f.area,subject:'Ciencias',period});
const restore=(f,restoreContent=true)=>{const s=f.db.record('s');return{action:'restore_subject',id:'s',revision:s.data.subjectRevision||s.updated_at,restoreContent};};
test('both areas restore safely as drafts, preserve files/history and recover final quotas',async()=>{
 for(const area of ['complexive','final_degree']){const f=fixture(area);try{
 const fileResponse=await FILE_POST(new Request(`${origin}/api/files?kind=material&fileName=archivo.pdf`,{method:'POST',headers:{origin,'sec-fetch-site':'same-origin'},body:new TextEncoder().encode('%PDF-1.4\nPrueba\n%%EOF')}));assert.equal(fileResponse.status,200);const file=await fileResponse.json();f.db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.fileKey',?) WHERE id='resource'").run(file.key);
 const old=f.db.record('old'),attempt=f.db.record('attempt');const removed=await remove(f);assert.equal(removed.archivedContent,5);assert.equal(removed.adjustedFinals,2);assert.equal(f.db.record('final').data.count,5);assert.equal(f.db.record('final-block').status,'archived');
 await post({action:'create_record',kind:'subject',title:'Ciencias',data:{area,period}},409);
 const recovered=await post(restore(f));assert.equal(recovered.restoredContent,5);assert.equal(recovered.restoredFinals,2);
 for(const [id,status] of [['s','published'],['topic','published'],['resource','draft'],['q','pending'],['block','pending'],['sim','draft'],['final','draft'],['final-block','draft'],['retired','archived']])assert.equal(f.db.record(id).status,status,id);
 assert.equal(f.db.record('final').data.count,10);assert.equal(f.db.record('final-block').data.count,4);assert.equal(f.db.record('resource').data.fileKey,file.key);assert.equal(f.objects.size,1);assert.deepEqual(f.db.record('old'),old);assert.deepEqual(f.db.record('attempt'),attempt);
 signIn('student');let data=await(await GET()).json();assert.ok(data.records.some(r=>r.id==='s'));assert.ok(!data.records.some(r=>r.id==='q'||r.id==='resource'));assert.equal('subjectArchive' in data.records.find(r=>r.id==='s').data,false);assert.equal((await FILE_GET(new Request(`${origin}/api/files?key=${encodeURIComponent(file.key)}`))).status,403);
 signIn();await post({action:'update_status',id:'resource',status:'published'});signIn('student');assert.equal((await FILE_GET(new Request(`${origin}/api/files?key=${encodeURIComponent(file.key)}`))).status,200);
 }finally{f.db.sql.close();}}
});
test('catalog-only recovery can recover its contents later and changed finals are never overwritten',async()=>{const f=fixture();try{await remove(f);await post(restore(f,false));assert.equal(f.db.record('s').status,'published');assert.equal(f.db.record('q').status,'archived');f.db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.count',7) WHERE id='final'").run();const result=await post(restore(f));assert.equal(result.restoredContent,5);assert.equal(result.restoredFinals,1);assert.equal(f.db.record('final').data.count,7);const again=await post(restore(f));assert.equal(again.restoredContent,0);assert.equal(again.restoredFinals,0);}finally{f.db.sql.close();}});
test('legacy recovery requires an explicit choice and refuses a conflicting active topic',async()=>{const f=fixture();try{f.db.sql.prepare("UPDATE records SET status='archived' WHERE id IN ('s','topic','q')").run();await post(restore(f,false));assert.equal(f.db.record('q').status,'archived');f.db.add('new-topic','topic','Nuevo tema','published',{area:f.area,period,subject:'Ciencias',number:1});await post(restore(f),409);assert.equal(f.db.record('topic').status,'archived');assert.equal(f.db.record('q').status,'archived');f.db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.number',2) WHERE id='new-topic'").run();await post(restore(f));assert.equal(f.db.record('topic').status,'published');assert.equal(f.db.record('q').status,'pending');}finally{f.db.sql.close();}});
test('restoration rejects unauthorized, historical, stale and missing records without a partial restore',async()=>{const f=fixture();try{await remove(f);const input=restore(f);signIn('student');await post(input,403);signIn();await post({...input,id:'missing'},404);await post({...input,revision:'old'},409);await post({...input,restoreContent:undefined},400);const batch=f.db.batch.bind(f.db);f.db.batch=async statements=>{f.db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.subjectRevision','concurrent') WHERE id='s'").run();return batch(statements);};await post(input,409);assert.equal(f.db.record('q').status,'archived');assert.equal(f.db.record('final').data.count,5);f.db.batch=batch;f.db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.period','2025-2026') WHERE id='s'").run();await post(restore(f),409);await post({action:'update_status',id:'s',status:'published'},400);}finally{f.db.sql.close();}});
test('a period activated during removal/restoration cannot change newly historical academic data',async()=>{for(const operation of ['remove','restore']){const f=fixture();try{if(operation==='restore')await remove(f);const original=f.db.record('q'),batch=f.db.batch.bind(f.db);f.db.batch=async statements=>{f.db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.current',0) WHERE id='period-current'").run();f.db.add('next','period','2027-2028','published',{current:true});return batch(statements);};await post(operation==='remove'?{action:'remove_subject',area:f.area,subject:'Ciencias',period}:restore(f),409);assert.deepEqual(f.db.record('q'),original);}finally{f.db.sql.close();}}});
test('academic creation racing with matter removal cannot leave new questions under an archived subject',async()=>{const f=fixture();try{const prepare=f.db.prepare.bind(f.db);f.db.prepare=query=>{const stmt=prepare(query),bind=stmt.bind;stmt.bind=(...args)=>{const bound=bind(...args);if(query.startsWith('INSERT INTO records (id,kind,group_id,title,status,data_json,created_by) SELECT')){const run=bound.run;bound.run=async()=>{f.db.sql.prepare("UPDATE records SET status='archived' WHERE id='s'").run();return run();};}return bound;};return stmt;};await post({action:'create_record',kind:'question',title:'Nueva',data:{area:f.area,period,subject:'Ciencias',topic:'Tema 1',prompt:'Pregunta válida',format:'Selección directa',options:['A','B','C','D'],correctIndex:0,source:'Libro',explanation:'Explicación'}},409);assert.equal(f.db.sql.prepare("SELECT COUNT(*) n FROM records WHERE kind='question'").get().n,1);}finally{f.db.sql.close();}});
