import assert from 'node:assert/strict';
import test from 'node:test';
import { POST, GET, FILE_POST, FILE_GET, RECONCILE_POST, TestDatabase, state, signIn } from './helpers/platform-api.mjs';
const origin='https://work.test';
class TestBucket{objects=new Map();async put(key,bytes,options){this.objects.set(key,{bytes:new Uint8Array(bytes).slice(),...options});}async head(key){return this.objects.get(key)||null;}async get(key){const o=this.objects.get(key);return o&&{body:o.bytes,size:o.bytes.length,customMetadata:o.customMetadata,arrayBuffer:async()=>o.bytes.slice().buffer,httpEtag:'"work"',writeHttpMetadata(h){h.set('content-type',o.httpMetadata.contentType);h.set('content-disposition',o.httpMetadata.contentDisposition);}};}async list(){return{objects:[...this.objects.keys()].map(key=>({key})),truncated:false};}async delete(key){this.objects.delete(key);}}
function fixture(){const db=new TestDatabase(),bucket=new TestBucket();state.env.DB=db;state.env.BUCKET=bucket;for(const who of ['teacher','student','other','foreign'])db.sql.prepare('INSERT INTO profiles(id,auth_id,email,full_name,role,status,group_id) VALUES(?,?,?,?,?,?,?)').run(who,`auth-${who}`,`${who==='teacher'?'profesor':who}@example.test`,who,who==='teacher'?'admin':'student','active',who==='teacher'?null:who==='foreign'?'g2':'g');db.add('period-current','period','2026-2027','published',{current:true});db.add('sim-ef-pilot','simulator','Sentinel','archived',{});for(const id of ['g','g2'])db.add(id,'group',id,'active',{plan:'Gold',planStatus:'active',endsAt:'2099-01-01',accessPolicyVersion:1});signIn();return{db,bucket};}
const request=(path,body)=>new Request(origin+path,{method:'POST',headers:{origin,'sec-fetch-site':'same-origin','content-type':'application/json'},body:JSON.stringify(body)});
async function post(body,status=200){const r=await POST(request('/api/platform',body)),j=await r.json();assert.equal(r.status,status,JSON.stringify(j));return j;}
async function upload(kind='submission'){const r=await FILE_POST(new Request(`${origin}/api/files?kind=${kind}&fileName=trabajo.pdf${kind==='review'?'&groupId=g':''}`,{method:'POST',headers:{origin,'sec-fetch-site':'same-origin'},body:'%PDF-1.4\nTrabajo\n%%EOF'})),j=await r.json();assert.equal(r.status,200,JSON.stringify(j));return j;}
async function download(key,status=200){const r=await FILE_GET(new Request(`${origin}/api/files?key=${encodeURIComponent(key)}`));assert.equal(r.status,status,await r.clone().text());}
const review=(db,id,extra={})=>({action:'review_work',id,revision:db.record(id).data.workRevision||db.record(id).updated_at,status:'changes_requested',reviewNotes:'Revisar la introducción.',dueAt:'2027-01-10',...extra});
test('submission/review history preserves every registered version and restricts downloads to its group',async()=>{const f=fixture();try{signIn('student');const a=await upload(),body={action:'submit_work',title:'Proyecto',workType:'planning',fileKey:a.key,fileName:a.fileName,notes:'Primera versión',workHistory:[{fileKey:'forged'}]},first=await post(body);assert.equal(f.db.record(first.id).data.workHistory.length,1);signIn();const corrected=await upload('review');await post(review(f.db,first.id,{reviewFileKey:corrected.key,reviewFileName:corrected.fileName}));signIn('student');const b=await upload();assert.equal((await post({...body,fileKey:b.key,notes:'Segunda versión'})).id,first.id);const current=f.db.record(first.id);assert.equal(current.data.workHistory.length,3);assert.deepEqual(current.data.workHistory.map(v=>v.version),[1,1,2]);assert.equal(current.data.reviewFileKey,null);assert.equal(current.data.reviewNotes,'');assert.equal(current.data.workHistory[1].notes,'Revisar la introducción.');for(const who of ['student','other']){signIn(who);const data=await(await GET()).json();assert.equal(data.records.find(row=>row.id===first.id).data.workHistory.length,3);await download(a.key);await download(corrected.key);await download(b.key);}signIn('foreign');assert.equal((await(await GET()).json()).records.some(row=>row.id===first.id),false);await download(a.key,403);await download(corrected.key,403);signIn();f.db.sql.prepare('DELETE FROM file_objects WHERE object_key IN (?,?)').run(a.key,corrected.key);const r=await RECONCILE_POST(request('/api/security/files/reconcile',{})),j=await r.json();assert.equal(r.status,200,JSON.stringify(j));assert.equal(j.registered,2);assert.equal(j.orphaned,0);assert.equal(f.bucket.objects.size,3);}finally{f.db.sql.close();}});
test('invalid/stale reviews preserve the active version and concurrent edits cannot overwrite it',async()=>{const f=fixture();try{signIn('student');const file=await upload(),work=await post({action:'submit_work',title:'Proyecto',workType:'planning',fileKey:file.key});await post(review(f.db,work.id),403);signIn();const original=f.db.record(work.id);await post(review(f.db,work.id,{dueAt:'2027-02-30'}),400);await post(review(f.db,work.id,{reviewNotes:''}),400);await post(review(f.db,work.id,{revision:'stale'}),409);assert.deepEqual(f.db.record(work.id),original);const prepare=f.db.prepare.bind(f.db);let fired=false;f.db.prepare=query=>{const statement=prepare(query),bind=statement.bind;statement.bind=(...values)=>{const bound=bind(...values),run=bound.run;bound.run=async()=>{if(!fired&&query.startsWith('UPDATE records SET status=?,data_json=')){fired=true;f.db.sql.prepare("UPDATE records SET data_json=json_set(data_json,'$.workRevision','concurrent') WHERE id=?").run(work.id);}return run();};return bound;};return statement;};await post(review(f.db,work.id),409);assert.equal(fired,true);assert.equal(f.db.record(work.id).data.workHistory.length,1);assert.equal(f.db.record(work.id).data.workRevision,'concurrent');}finally{f.db.sql.close();}});
test('legacy requests keep their available version and the history bound never truncates saved events',async()=>{const f=fixture();try{f.db.add('legacy','submission','Anterior','in_review',{revisions:2,notes:'Disponible',submittedByName:'Alumno',reviewNotes:'Corrección anterior'},'g','student');await post(review(f.db,'legacy',{status:'in_review'}));let row=f.db.record('legacy');assert.equal(row.data.workHistory.length,3);assert.equal(row.data.workHistory[0].legacy,true);assert.equal(row.data.workHistory[0].version,3);const data={...row.data,workHistory:Array.from({length:200},(_,i)=>({...row.data.workHistory[0],id:String(i)}))};f.db.sql.prepare('UPDATE records SET data_json=? WHERE id=?').run(JSON.stringify(data),'legacy');const before=f.db.record('legacy');await post(review(f.db,'legacy'),400);assert.deepEqual(f.db.record('legacy'),before);}finally{f.db.sql.close();}});
