"use client";

import { useState } from "react";
import { FolderCog, Plus, Pencil, RefreshCw } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { buildAcademicTopics, nextTopicNumber, normalizedTopicDefinition, topicAliases, topicKey, topicMatches, type AcademicScope, type AcademicTopic, type TopicRecord } from "@/lib/academic-topics";

type Mutate = (body: Record<string, unknown>, success?: string) => Promise<boolean>;
const selectClass = "min-h-11 w-full rounded-xl border bg-white px-3 text-sm";

export function AcademicTopicSelector({ scope, topicRows, content, value, topicId = "", onChange, mutate, disabled = false }: { scope: AcademicScope; topicRows: TopicRecord[]; content: TopicRecord[]; value: string; topicId?: string; onChange: (title: string, id: string) => void; mutate: Mutate; disabled?: boolean }) {
  const topics = buildAcademicTopics(topicRows, content, scope), suggestedNumber = topics.length >= 999 ? 999 : nextTopicNumber(topics);
  const selected = topics.find(topic => topicId ? topic.id === topicId : topicAliases(topic).has(topicKey(value)));
  const [number, setNumber] = useState(""), [name, setName] = useState(""), [busy, setBusy] = useState(false);
  return <div className="space-y-2">
    <select aria-label="Tema del contenido" className={selectClass} value={selected?.id || ""} disabled={disabled || !scope.subject || busy} onChange={event => { const topic = topics.find(item => item.id === event.target.value); onChange(topic?.title || "", topic && !topic.legacy ? topic.id : ""); }}>
      <option value="">Selecciona un tema</option>{topics.map(topic => <option key={topic.id} value={topic.id}>{topic.title}</option>)}
    </select>
    {scope.subject && <details className="rounded-xl border bg-slate-50 p-3 text-sm"><summary className="cursor-pointer font-semibold">Crear un tema para esta materia</summary><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Input type="number" min={1} max={999} aria-label="Número del nuevo tema" className="sm:w-24" value={number || String(suggestedNumber)} disabled={disabled || busy} onChange={event => setNumber(event.target.value)}/><Input aria-label="Nombre del nuevo tema" value={name} maxLength={150} disabled={disabled || busy} placeholder="Nombre del tema" onChange={event => setName(event.target.value)}/><Button type="button" disabled={disabled || busy || topics.length >= 999} onClick={async () => { let definition; try { definition = normalizedTopicDefinition(Number(number || suggestedNumber), name); } catch (error) { return toast.error(error instanceof Error ? error.message : "Revisa el tema."); } setBusy(true); try { if (await mutate({ action: "save_academic_topic", ...scope, ...definition }, "Tema creado.")) { onChange(definition.title, ""); setNumber(""); setName(""); } } finally { setBusy(false); } }}><Plus/> Crear</Button></div><p className="mt-2 text-xs text-slate-500">Se usará el mismo tema en materiales, bloques y práctica.</p></details>}
  </div>;
}

export function AcademicTopicManager({ scope, topicRows, content, mutate }: { scope: AcademicScope; topicRows: TopicRecord[]; content: TopicRecord[]; mutate: Mutate }) {
  const topics = buildAcademicTopics(topicRows, content, scope), suggestedNumber = topics.length >= 999 ? 999 : nextTopicNumber(topics);
  const [open, setOpen] = useState(false), [id, setId] = useState(""), [number, setNumber] = useState(""), [name, setName] = useState(""), [busy, setBusy] = useState(false);
  const reset = () => { setId(""); setNumber(""); setName(""); };
  return <Dialog open={open} onOpenChange={value => { if (!busy) { setOpen(value); if (value) reset(); } }}><DialogTrigger asChild><Button variant="outline" disabled={!scope.subject}><FolderCog/> Gestionar temas</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Temas de {scope.subject}</DialogTitle><DialogDescription>El número determina el orden. Al cambiar un nombre se conservan sus materiales, preguntas e historial.</DialogDescription></DialogHeader>
    <div className="grid grid-cols-[90px_1fr] gap-3"><label className="space-y-2 text-sm font-semibold">Número<Input type="number" min={1} max={999} value={number || String(suggestedNumber)} disabled={busy} onChange={event => setNumber(event.target.value)}/></label><label className="space-y-2 text-sm font-semibold">Nombre<Input value={name} maxLength={150} disabled={busy} onChange={event => setName(event.target.value)} placeholder="Ej.: Ecosistemas"/></label></div>
    <div className="flex flex-wrap gap-2"><Button className="bg-[#003f32]" disabled={busy || (!id && topics.length >= 999)} onClick={async () => { let definition; try { definition = normalizedTopicDefinition(Number(number || suggestedNumber), name); } catch (error) { return toast.error(error instanceof Error ? error.message : "Revisa el tema."); } setBusy(true); try { if (await mutate({ action: "save_academic_topic", ...scope, id, ...definition }, id ? "Tema actualizado." : "Tema creado.")) reset(); } finally { setBusy(false); } }}>{busy ? <RefreshCw className="animate-spin"/> : <Plus/>} {id ? "Guardar cambios" : "Añadir tema"}</Button>{id && <Button variant="outline" disabled={busy} onClick={reset}>Cancelar edición</Button>}<Button variant="outline" disabled={busy} onClick={async () => { setBusy(true); try { await mutate({ action: "sync_academic_topics" }, "Temas existentes organizados."); } finally { setBusy(false); } }}><RefreshCw/> Organizar existentes</Button></div>
    <div className="space-y-2">{topics.length ? topics.map(topic => <article key={topic.id} className="flex items-center justify-between gap-3 rounded-2xl border bg-white p-3"><div className="min-w-0"><p className="font-semibold">{topic.title}</p><p className="mt-1 text-xs text-slate-500">{content.filter(row => row.status !== "archived" && topicMatches(row.data, topic)).length} contenido(s) asociados{topic.legacy ? " · Pendiente de organizar" : topic.needsReview ? " · Revisar número y nombre" : ""}</p></div><Button size="sm" variant="outline" disabled={busy || topic.legacy} onClick={() => { setId(topic.id); setNumber(String(topic.number)); setName(topic.name); }}><Pencil/> Editar</Button></article>) : <p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">Añade el primer tema para comenzar a cargar materiales y bloques.</p>}</div>
  </DialogContent></Dialog>;
}

export function AcademicTopicNavigation({ topics, value, onChange, resources, questions, description = "Elige un tema para ver sus materiales y practicar." }: { topics: AcademicTopic[]; value: string; onChange: (id: string) => void; resources: TopicRecord[]; questions: TopicRecord[]; description?: string }) {
  if (!topics.length) return <p className="rounded-2xl border bg-slate-50 p-4 text-sm text-slate-600">Los temas aparecerán cuando el profesor los prepare.</p>;
  return <section className="space-y-3 rounded-[22px] border bg-white p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-bold">Temas de la materia</h3><p className="mt-1 text-sm text-slate-500">{description}</p></div><Button size="sm" variant={value === "all" ? "default" : "outline"} onClick={() => onChange("all")}>Todos los temas</Button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{topics.map(topic => { const materials = resources.filter(row => row.status !== "archived" && topicMatches(row.data, topic)).length, approved = questions.filter(row => row.status === "approved" && topicMatches(row.data, topic)).length; return <button type="button" key={topic.id} aria-pressed={value === topic.id} onClick={() => onChange(topic.id)} className={`min-h-20 rounded-2xl border p-3 text-left ${value === topic.id ? "border-[#d6a32b] bg-[#fff9eb] ring-2 ring-[#d6a32b]/15" : "bg-white hover:border-slate-400"}`}><p className="font-semibold">{topic.title}</p><p className="mt-2 text-xs text-slate-500">{materials} material(es) · {approved} pregunta(s) aprobada(s)</p></button>; })}</div></section>;
}
