"use client";
import { useEffect, useState } from "react";
import { LockKeyhole } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { passwordAction } from "@/components/password-access";

type Person = { id: string; email: string; full_name: string; role: string; status: string };
type AuthSettings = { method: string; configured: boolean; assignments: Array<{ profile_id: string; state: string; must_change_password: number }> };
export function PasswordAdministration({ profiles }: { profiles: Person[] }) {
  const [settings, setSettings] = useState<AuthSettings | null>(null);
  const [id, setId] = useState(""); const [password, setPassword] = useState(""); const [current, setCurrent] = useState("");
  const [show, setShow] = useState(false); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  useEffect(() => { let active = true; fetch("/api/auth", { cache: "no-store" }).then(async r => { if (!r.ok) throw new Error(); return await r.json() as AuthSettings; }).then(value => { if (active) setSettings(value); }).catch(() => { if (active) setError("No se pudo consultar la configuración del acceso."); }); return () => { active = false; }; }, []);
  const selected = profiles.find(profile => profile.id === id), assigned = settings?.assignments.find(row => row.profile_id === id);
  return <section className="rounded-[24px] border bg-white p-5 sm:p-6"><div className="flex items-start gap-3"><LockKeyhole className="mt-1 shrink-0 text-[#8a5e08]"/><div><h2 className="text-lg font-bold">Contraseñas de las cuentas registradas</h2><p className="mt-2 text-sm leading-6 text-slate-600">Primero registra el correo y asigna su grupo. Luego entrega una contraseña inicial única: el estudiante tendrá que cambiarla al entrar.</p></div></div>
    {!settings?.configured ? <p role="status" className="mt-4 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-900">{settings ? "Preparado para el acceso independiente. Falta conectar el servicio de autenticación; esta página sigue usando ChatGPT." : "Comprobando la configuración de acceso…"}</p> : <form className="mt-5 grid gap-4 sm:grid-cols-2" onSubmit={async event => { event.preventDefault(); if (busy || !selected) return; setBusy(true); setNotice(""); setError(""); try { await passwordAction({ action: "set_password", profileId: id, password, ...(settings.method === "password" ? { currentPassword: current } : {}) }); setPassword(""); setCurrent(""); setNotice(`Contraseña asignada a ${selected.email}. Al entrar deberá cambiarla.`); const r = await fetch("/api/auth", { cache: "no-store" }); if (r.ok) setSettings(await r.json()); } catch (issue) { setError(issue instanceof Error ? issue.message : "No se pudo asignar la contraseña."); } finally { setBusy(false); } }}>
      <label className="text-sm font-semibold">Cuenta registrada<select className="mt-2 min-h-12 w-full rounded-xl border bg-white px-3" value={id} onChange={event => { setId(event.target.value); setPassword(""); setNotice(""); }} required disabled={busy}><option value="">Selecciona una cuenta</option>{profiles.filter(p => ["active", "invited"].includes(p.status)).map(profile => <option key={profile.id} value={profile.id}>{profile.full_name} · {profile.email}{profile.role === "admin" ? " · Profesor" : ""}</option>)}</select></label>
      <label className="text-sm font-semibold">{assigned ? "Nueva contraseña temporal" : "Contraseña inicial"}<Input className="mt-2 h-12" type={show ? "text" : "password"} autoComplete="new-password" minLength={15} required disabled={busy} value={password} onChange={event => setPassword(event.target.value)}/></label>
      {settings.method === "password" && <label className="text-sm font-semibold">Tu contraseña de administrador<Input className="mt-2 h-12" type="password" autoComplete="current-password" value={current} onChange={event => setCurrent(event.target.value)} required disabled={busy}/></label>}
      <div className="flex flex-wrap items-center gap-3 sm:col-span-2"><Button type="button" variant="outline" disabled={busy} onClick={() => { const bytes = crypto.getRandomValues(new Uint8Array(20)); const alphabet = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789"; setPassword(Array.from(bytes, b => alphabet[b % alphabet.length]).join("")); setShow(true); }}>Generar contraseña</Button><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={show} onChange={event => setShow(event.target.checked)}/>Mostrar contraseña</label><Button type="submit" className="bg-[#003f32]" disabled={busy || !selected}>{busy ? "Guardando…" : assigned ? "Restablecer contraseña" : "Asignar contraseña"}</Button></div>
      <p className="text-xs leading-5 text-slate-500 sm:col-span-2">Guarda la contraseña temporal en un lugar privado antes de confirmar. Al guardar se vacía el campo. Restablecerla cancela las sesiones anteriores; el historial académico se conserva.</p>
    </form>}
    {notice && <p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>}{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}
  </section>;
}

export function PasswordAccountActions({ method }: { method: "sites" | "password" }) {
  const [changing, setChanging] = useState(false); const [current, setCurrent] = useState(""); const [password, setPassword] = useState("");
  const [confirmation, setConfirmation] = useState(""); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  if (method === "sites") return <Button asChild className="mt-6 w-full bg-white text-[#003f32]"><a href="/signout-with-chatgpt?return_to=/" target="_top">Cerrar sesión</a></Button>;
  return <div className="mt-5 space-y-3">{changing && <form className="space-y-3" onSubmit={async event => { event.preventDefault(); if (busy) return; if (password !== confirmation) { setNotice("Las contraseñas nuevas no coinciden."); return; } setBusy(true); try { await passwordAction({ action: "change_password", currentPassword: current, password }); setCurrent(""); setPassword(""); setConfirmation(""); setChanging(false); setNotice("Contraseña actualizada. Las otras sesiones se cerraron."); } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo guardar."); } finally { setBusy(false); } }}>
    {[ ["Contraseña actual", current, setCurrent, "current-password"], ["Nueva contraseña", password, setPassword, "new-password"], ["Repite la nueva", confirmation, setConfirmation, "new-password"] ].map(([label, value, setter, autocomplete]) => <label key={String(label)} className="block text-sm">{String(label)}<Input type="password" className="mt-2 bg-white text-[#15352d]" autoComplete={String(autocomplete)} value={String(value)} onChange={event => (setter as (value: string) => void)(event.target.value)} required disabled={busy}/></label>)}<p className="text-xs text-slate-300">Usa al menos 15 caracteres y una contraseña única.</p><Button type="submit" disabled={busy} className="w-full bg-white text-[#003f32]">Guardar contraseña</Button>
  </form>}<Button variant="outline" className="w-full bg-white text-[#003f32]" disabled={busy} onClick={() => { setChanging(!changing); setCurrent(""); setPassword(""); setConfirmation(""); }}>{changing ? "Cancelar cambio" : "Cambiar contraseña"}</Button><Button className="w-full bg-white text-[#003f32]" disabled={busy} onClick={async () => { setBusy(true); try { await passwordAction({ action: "logout" }); window.location.reload(); } catch (error) { setNotice(error instanceof Error ? error.message : "No se pudo cerrar sesión."); setBusy(false); } }}>Cerrar sesión</Button>{notice && <p role="status" className="text-sm leading-6">{notice}</p>}</div>;
}
