"use client";
import { useState } from 'react';
import { CalendarDays, Check, Plus } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogTrigger } from '@/components/ui/dialog';
import { AlertDialog, AlertDialogTrigger, AlertDialogContent, AlertDialogHeader, AlertDialogTitle, AlertDialogDescription, AlertDialogFooter, AlertDialogCancel, AlertDialogAction } from '@/components/ui/alert-dialog';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
type Row = { id: string; title: string; kind: string; updated_at: string; data: Record<string, unknown> };
export function PeriodManagement({ rows, all, mutate }: { rows: Row[]; all: Row[]; mutate: (body: Record<string, unknown>, success?: string) => Promise<boolean> }) {
  const [open, setOpen] = useState(false), [title, setTitle] = useState(''), [note, setNote] = useState('');
  const current = rows.find(row => row.data.current === true);
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-widest text-[#8a5e08]">Periodos y convocatorias</p><h1 className="mt-2 text-3xl font-extrabold">Vigencia e historial</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Vigente: {current?.title || 'Sin selección'}. Activar una convocatoria cambia los contenidos que pueden usar los estudiantes. Cada archivo e intento conserva su periodo.</p></div><Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/> Crear periodo</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Nueva convocatoria</DialogTitle><DialogDescription>Se crea en preparación. Después podrás activarla. No se copian ni trasladan contenidos.</DialogDescription></DialogHeader><label className="space-y-2 text-sm font-semibold">Periodo<Input value={title} onChange={e=>setTitle(e.target.value)} placeholder="2027-2028" maxLength={9}/></label><label className="space-y-2 text-sm font-semibold">Nota<Textarea maxLength={4000} value={note} onChange={e=>setNote(e.target.value)}/></label><Button onClick={async()=>{if(await mutate({action:'create_period',title,note},'Periodo creado en preparación.')){setTitle('');setNote('');setOpen(false);}}}>Guardar periodo</Button></DialogContent></Dialog></div>
    <div className="grid gap-4 md:grid-cols-2">{rows.toSorted((a,b)=>b.title.localeCompare(a.title)).map(row=><article key={row.id} className={`rounded-3xl border bg-white p-6 ${row.data.current?'border-[#d6a32b] ring-2 ring-amber-100':''}`}><div className="flex justify-between gap-3"><CalendarDays className="size-6 text-[#8a5e08]"/><span className="text-sm font-semibold">{row.data.current?'Vigente':'Disponible para activar'}</span></div><h2 className="mt-4 text-2xl font-extrabold">{row.title}</h2><p className="mt-2 text-sm text-slate-600">{String(row.data.note||'')}</p><p className="mt-4 text-sm text-slate-500">{all.filter(item=>item.data.period===row.title).length} registros asociados</p>{!row.data.current&&<AlertDialog><AlertDialogTrigger asChild><Button className="mt-4" variant="outline"><Check/> Activar convocatoria</Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>¿Activar {row.title}?</AlertDialogTitle><AlertDialogDescription>Será el periodo vigente para todas las áreas. Los contenidos de {current?.title||'la convocatoria anterior'} quedarán en su historial y no se trasladarán. Prepara materias, temas y contenidos propios de {row.title} antes de que los estudiantes los necesiten.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>mutate({action:'activate_period',id:row.id,currentId:current?.id||'',revision:current?.data.selectionRevision||current?.updated_at||''},`${row.title} es el periodo vigente.`)}>Activar {row.title}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</article>)}</div>
  </div>;
}
