"use client";

import { useId, useState } from "react";
import { Check, ChevronDown, Clock3, RefreshCw, ShieldCheck, SlidersHorizontal, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { confirmDrafts, useDraftGuard } from "@/components/draft-guard";
import { PLAN_FEATURES, PLAN_NAMES, canUsePlanFeature, defaultFeatureEnabled, defaultPlanCatalog, editableGroupOverrides, groupReviewLimit, isPlanActive, isPlanName, type FeatureOverride, type FeatureOverrides, type PlanCatalog, type PlanFeature, type PlanName, type PlanTemplate } from "@/lib/plans";

type Mutate = (body: Record<string, unknown>, success?: string) => Promise<boolean>;
type GroupRow = { id: string; title: string; data: Record<string, unknown> };
const selectClass = "min-h-11 rounded-xl border bg-white px-3 text-sm";
const allFeatures = (): FeatureOverrides => Object.fromEntries(PLAN_FEATURES.map(feature => [feature.id, "allow"])) as FeatureOverrides;
const groups = [...new Set(PLAN_FEATURES.map(feature => feature.group))];
function changeOverride(previous: FeatureOverrides, key: PlanFeature, value: string) { const next = { ...previous }; if (value === "default") delete next[key]; else next[key] = value as FeatureOverride; return next; }
const defaultEnabled = (catalog: PlanCatalog, plan: PlanName, feature: PlanFeature) => catalog[plan].featureOverrides[feature] ? catalog[plan].featureOverrides[feature] === "allow" : defaultFeatureEnabled(plan, feature);

export function PlanOptionGrid({ plan, catalog, overrides, setOverrides, disabled = false, template = false }: { plan: PlanName; catalog: PlanCatalog; overrides: FeatureOverrides; setOverrides: (next: FeatureOverrides) => void; disabled?: boolean; template?: boolean }) {
  const prefix = useId();
  return <div className="grid items-start gap-4 xl:grid-cols-2">{groups.map(group => <section key={group} className="overflow-hidden rounded-2xl border bg-white"><h3 className="border-b bg-[#f7f9f6] px-4 py-3 text-sm font-bold">{group}</h3><div className="divide-y">{PLAN_FEATURES.filter(feature => feature.group === group).map(feature => {
    const included = template ? defaultFeatureEnabled(plan, feature.id) : defaultEnabled(catalog, plan, feature.id), state = overrides[feature.id] || "default";
    return <div key={feature.id} className="flex flex-col gap-2 px-4 py-3 sm:flex-row sm:items-center sm:justify-between"><label htmlFor={`${prefix}-${feature.id}`} className="min-w-0 flex-1 text-sm"><span className="block font-semibold">{feature.label}</span><span className="mt-1 block text-xs text-slate-500">{state === "allow" ? "Habilitado manualmente" : state === "deny" ? "Desactivado manualmente" : included ? "Incluido; respeta el plan mínimo del contenido" : "No incluido en la configuración base"}</span></label><select id={`${prefix}-${feature.id}`} disabled={disabled} className={`${selectClass} w-full shrink-0 sm:w-44`} value={state} onChange={event => setOverrides(changeOverride(overrides, feature.id, event.target.value))}><option value="default">{template ? "Base" : "Del plan"}: {included ? "incluido" : "no incluido"}</option><option value="allow">Activar opción</option><option value="deny">Desactivar opción</option></select></div>;
  })}</div></section>)}</div>;
}

function TemplateEditor({ value, catalog, groupCount, mutate }: { value: PlanTemplate; catalog: PlanCatalog; groupCount: number; mutate: Mutate }) {
  const [overrides, setOverrides] = useState<FeatureOverrides>(value.featureOverrides), [reviews, setReviews] = useState(value.reviewLimit), [busy, setBusy] = useState(false);
  const dirty = JSON.stringify(overrides) !== JSON.stringify(value.featureOverrides) || reviews !== value.reviewLimit;
  useDraftGuard(`template:${value.plan}`, dirty, [overrides, reviews]);
  const included = PLAN_FEATURES.filter(feature => (overrides[feature.id] || "default") === "allow" || (!overrides[feature.id] && defaultFeatureEnabled(value.plan, feature.id))).length;
  return <details data-draft-scope={`template:${value.plan}`} className="group overflow-hidden rounded-[24px] border bg-white">
    <summary className="flex cursor-pointer list-none items-center justify-between gap-4 p-5 sm:p-6"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-[#8a5e08]">Beneficios por plan</p><h2 className="mt-1 text-2xl font-extrabold">{value.plan}</h2><p className="mt-2 text-sm text-slate-500">{included} de {PLAN_FEATURES.length} opciones · {groupCount} grupo(s) activo(s)</p></div><ChevronDown className="size-5 shrink-0 text-[#55766a] transition-transform group-open:rotate-180"/></summary>
    <div className="space-y-5 border-t p-4 sm:p-6">
      <p className="rounded-xl bg-[#f0f6f2] p-4 text-sm leading-6">Estos beneficios se aplican a todos los grupos con {value.plan}. Las excepciones que configures para un grupo tienen prioridad.</p>
      <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => setOverrides(allFeatures())}>Habilitar todas las opciones</Button><Button variant="outline" disabled={busy} onClick={() => { setOverrides({}); setReviews(defaultPlanCatalog()[value.plan].reviewLimit); }}><RefreshCw/> Restaurar valores predeterminados</Button></div>
      <PlanOptionGrid plan={value.plan} catalog={catalog} overrides={overrides} setOverrides={setOverrides} disabled={busy} template/>
      <label className="block max-w-sm space-y-2 text-sm font-semibold">Correcciones por proyecto<Input type="number" min={0} max={100} step={1} value={reviews} disabled={busy} onChange={event => setReviews(Number(event.target.value))}/><span className="block text-xs font-normal leading-5 text-slate-500">Se aplica cuando el grupo tiene habilitado ese tipo de trabajo. Plata parte de 1 y Gold de 3.</span></label>
      <div className="flex flex-wrap items-center justify-between gap-3 border-t pt-4"><p className="text-xs leading-5 text-slate-500">Los cambios se aplican al guardar. Activar una opción permite su contenido publicado, aunque tenga un plan mínimo superior.</p><Button className="bg-[#003f32]" disabled={busy || !dirty || !Number.isInteger(reviews) || reviews < 0 || reviews > 100} onClick={async () => { setBusy(true); try { await mutate({ action: "save_plan_template", plan: value.plan, revision: value.revision, featureOverrides: overrides, reviewLimit: reviews }, `Beneficios de ${value.plan} actualizados.`); } finally { setBusy(false); } }}>{busy ? <RefreshCw className="animate-spin"/> : <Check/>} Guardar beneficios de {value.plan}</Button></div>
    </div>
  </details>;
}

function GroupEditor({ row, catalog, mutate }: { row: GroupRow; catalog: PlanCatalog; mutate: Mutate }) {
  const [plan, setPlan] = useState<PlanName>(isPlanName(row.data.plan) ? row.data.plan : "Bronce"), [days, setDays] = useState(30), [mode, setMode] = useState<"plan" | "custom">(Object.keys(editableGroupOverrides(row.data)).length || row.data.reviewLimit !== undefined ? "custom" : "plan"), [overrides, setOverrides] = useState(editableGroupOverrides(row.data)), [reviews, setReviews] = useState<number | null>(typeof row.data.reviewLimit === "number" ? row.data.reviewLimit : null), [busy, setBusy] = useState(false);
  const revision = row.data.accessRevision || "initial", active = isPlanActive(row.data.planStatus, row.data.endsAt);
  const selection = mode === "plan" ? {} : overrides, preview = { ...row.data, plan, planStatus: "active", endsAt: "9999-12-31T23:59:59.000Z", permissions: [], featureOverrides: selection, accessPolicyVersion: 1, reviewLimit: mode === "plan" ? undefined : reviews ?? undefined };
  const included = PLAN_FEATURES.filter(feature => canUsePlanFeature(preview, feature.id, catalog)).length;
  const initialMode = Object.keys(editableGroupOverrides(row.data)).length || row.data.reviewLimit !== undefined ? "custom" : "plan";
  useDraftGuard(`group:${row.id}`, plan !== (isPlanName(row.data.plan) ? row.data.plan : "Bronce") || days !== 30 || mode !== initialMode || JSON.stringify(overrides) !== JSON.stringify(editableGroupOverrides(row.data)) || reviews !== (typeof row.data.reviewLimit === "number" ? row.data.reviewLimit : null), [plan, days, mode, overrides, reviews]);
  return <section data-draft-scope={`group:${row.id}`} className="space-y-5 rounded-[24px] border bg-white p-4 sm:p-6">
    <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-extrabold">{row.title}</h2><p className="mt-2 text-sm text-slate-500">Plan actual: {String(row.data.plan || "Sin plan")}{typeof row.data.endsAt === "string" && Number.isFinite(Date.parse(row.data.endsAt)) ? ` · Vence ${new Intl.DateTimeFormat("es-EC", { dateStyle: "medium", timeZone: "America/Guayaquil" }).format(new Date(row.data.endsAt))}` : " · Sin vigencia"}</p></div><Badge className={active ? "bg-emerald-100 text-emerald-800" : "bg-amber-100 text-amber-800"}>{active ? "Plan vigente" : "Pendiente o vencido"}</Badge></div>
    <div className="grid gap-4 sm:grid-cols-3"><label className="space-y-2 text-sm font-semibold">Plan para este grupo<select className={`${selectClass} w-full`} value={plan} disabled={busy} onChange={event => setPlan(event.target.value as PlanName)}>{PLAN_NAMES.map(name => <option key={name}>{name}</option>)}</select></label><label className="space-y-2 text-sm font-semibold">Opciones de acceso<select className={`${selectClass} w-full`} value={mode} disabled={busy} onChange={event => setMode(event.target.value as "plan" | "custom")}><option value="plan">Usar todos los beneficios del plan</option><option value="custom">Personalizar para este grupo</option></select></label><label className="space-y-2 text-sm font-semibold">Días al activar<Input type="number" min={1} max={365} step={1} value={days} disabled={busy} onChange={event => setDays(Number(event.target.value))}/></label></div>
    <p className="rounded-xl bg-[#f3f7f3] p-4 text-sm leading-6"><strong>{included} opciones habilitadas al activar.</strong> {mode === "plan" ? `Se usarán los beneficios guardados de ${plan}, sin excepciones anteriores.` : "Las opciones que actives o desactives aquí se aplicarán solamente a este grupo."}</p>
    <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={() => { setMode("custom"); setOverrides(allFeatures()); }}>Habilitar todas las opciones</Button><Button variant="outline" disabled={busy} onClick={() => { setMode("plan"); setOverrides({}); setReviews(null); }}>Volver a los beneficios del plan</Button></div>
    <PlanOptionGrid plan={plan} catalog={catalog} overrides={selection} setOverrides={setOverrides} disabled={busy || mode === "plan"}/>
    {mode === "custom" && <div className="grid gap-3 rounded-2xl bg-slate-50 p-4 sm:grid-cols-2"><label className="space-y-2 text-sm font-semibold">Correcciones por proyecto<select className={`${selectClass} w-full`} disabled={busy} value={reviews === null ? "plan" : "custom"} onChange={event => setReviews(event.target.value === "plan" ? null : groupReviewLimit(preview, catalog))}><option value="plan">Usar límite de {plan}: {catalog[plan].reviewLimit}</option><option value="custom">Definir un límite para el grupo</option></select></label>{reviews !== null && <label className="space-y-2 text-sm font-semibold">Cantidad de correcciones<Input type="number" min={0} max={100} step={1} value={reviews} disabled={busy} onChange={event => setReviews(Number(event.target.value))}/></label>}</div>}
    <div className="space-y-3 border-t pt-4"><p className="text-xs leading-5 text-slate-500">Guardar permisos conserva la vigencia y el plan actual. Activar plan aplica la selección y establece la vigencia desde hoy. Las excepciones de acceso también vencen con el plan.</p><div className="flex flex-wrap justify-end gap-2"><Button variant="outline" disabled={busy || plan !== row.data.plan || (reviews !== null && (!Number.isInteger(reviews) || reviews < 0 || reviews > 100))} onClick={async () => { setBusy(true); try { await mutate({ action: "save_group_permissions", id: row.id, revision, permissionMode: mode, featureOverrides: overrides, reviewLimit: reviews }, "Permisos guardados; la vigencia se conserva."); } finally { setBusy(false); } }}><SlidersHorizontal/> Guardar permisos del grupo</Button><Button className="bg-[#003f32]" disabled={busy || !Number.isInteger(days) || days < 1 || days > 365 || (reviews !== null && (!Number.isInteger(reviews) || reviews < 0 || reviews > 100))} onClick={async () => { setBusy(true); try { await mutate({ action: "activate_plan", id: row.id, revision, plan, days, permissionMode: mode, featureOverrides: overrides, reviewLimit: reviews }, `Plan ${plan} activado con las opciones seleccionadas.`); } finally { setBusy(false); } }}>{busy ? <RefreshCw className="animate-spin"/> : <Clock3/>} Activar {plan} · {days || "—"} días</Button></div></div>
  </section>;
}

export function PlanPermissions({ rows, catalog, mutate }: { rows: GroupRow[]; catalog: PlanCatalog; mutate: Mutate }) {
  const [tab, setTab] = useState("plans"), [selected, setSelected] = useState(rows[0]?.id || ""), row = rows.find(group => group.id === selected) || rows[0];
  return <div className="space-y-6"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#8a5e08]">Planes y permisos</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight">Beneficios por plan y por grupo</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-600">Primero define qué incluye Bronce, Plata o Gold. Después activa un plan para el grupo o personaliza sus opciones.</p></div>
    <Tabs value={tab} onValueChange={value => { if (confirmDrafts()) setTab(value); }}><TabsList className="grid h-auto w-full grid-cols-2 rounded-2xl border bg-white p-1 sm:w-fit"><TabsTrigger className="min-h-11 gap-2 whitespace-normal" value="plans"><WalletCards className="size-4"/> Beneficios de los planes</TabsTrigger><TabsTrigger className="min-h-11 gap-2 whitespace-normal" value="groups"><Users className="size-4"/> Activación y permisos por grupo</TabsTrigger></TabsList>
      <TabsContent value="plans" className="mt-5 space-y-4"><p className="text-sm leading-6 text-slate-500">Abre un plan para ver sus opciones. «Base» mantiene lo acordado; «Activar opción» amplía el acceso y «Desactivar opción» lo retira.</p>{PLAN_NAMES.map(plan => <TemplateEditor key={`${plan}:${catalog[plan].revision}`} value={catalog[plan]} catalog={catalog} groupCount={rows.filter(group => group.data.plan === plan && isPlanActive(group.data.planStatus, group.data.endsAt)).length} mutate={mutate}/>)}</TabsContent>
      <TabsContent value="groups" className="mt-5 space-y-5">{row ? <><label className="block max-w-xl space-y-2 text-sm font-semibold">Grupo que deseas configurar<select className={`${selectClass} w-full`} value={row.id} onChange={event => { if (confirmDrafts()) setSelected(event.target.value); }}>{rows.map(group => <option key={group.id} value={group.id}>{group.title} · {String(group.data.plan || "Sin plan")}</option>)}</select></label><GroupEditor key={`${row.id}:${row.data.accessRevision || "initial"}`} row={row} catalog={catalog} mutate={mutate}/></> : <div className="rounded-[24px] border border-dashed bg-white p-8 text-center"><Users className="mx-auto size-8 text-slate-400"/><h2 className="mt-3 font-bold">Primero crea un grupo</h2><p className="mt-2 text-sm text-slate-500">En Estudiantes y grupos podrás crear el grupo y registrar sus correos.</p></div>}</TabsContent>
    </Tabs>
    <p className="flex items-start gap-3 rounded-2xl bg-[#edf4ef] p-4 text-sm leading-6 text-[#365b4b]"><ShieldCheck className="mt-1 size-5 shrink-0"/> Los beneficios habilitan contenidos publicados y funciones de estudiante. El registro del correo y la cuenta activa siguen siendo obligatorios.</p>
  </div>;
}
