"use client";
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { emptyFilters, filterRecords, paginateRecords, type ListAccessors, type ListFilters } from '@/lib/record-lists';
export function useRecordList<T>(rows:readonly T[], accessors:Partial<ListAccessors<T>>={}, options:{scope?:string;statuses?:string[];revision?:string}={}) {
  const [filters,setFilters]=useState<ListFilters>(()=>{const query=typeof window==='undefined'?'':new URLSearchParams(window.location.hash.split('?').slice(1).join('?')).get('status')||'';return{...emptyFilters,status:typeof window!=='undefined'&&options.scope&&window.location.hash.split('/')[1]===options.scope&&options.statuses?.includes(query)?query:''};}),[size,setSize]=useState(10),[cursor,setCursor]=useState({key:'',page:0});
  type Basic={title?:string;status?:string;group_id?:string|null;created_at?:string;data?:Record<string,unknown>};
  const fields:ListAccessors<T>={text:row=>String((row as Basic).title||''),status:row=>String((row as Basic).status||''),group:row=>String((row as Basic).group_id||''),at:row=>String((row as Basic).created_at||''),period:row=>String((row as Basic).data?.period||''),...accessors};
  const filtered=filterRecords(rows,filters,fields),key=JSON.stringify([filters,options.revision,size]),pagination=paginateRecords(filtered,cursor.key===key?cursor.page:0,size);
  return{filters,filtered,pageRows:pagination.rows,pagination,size,change:(name:keyof ListFilters,value:string)=>setFilters(previous=>({...previous,[name]:value})),reset:()=>setFilters({...emptyFilters}),setSize,page:(page:number)=>setCursor({key,page})};
}
type ListState = Pick<ReturnType<typeof useRecordList>, 'filters'|'pagination'|'size'|'change'|'reset'|'setSize'|'page'>;
const select='min-h-11 w-full rounded-xl border bg-white px-3 text-sm';
export function RecordListControls({list,statuses=[],groups,periods,placeholder='Buscar registros',dateLabel='Fecha del registro'}:{list:ListState;statuses?:[string,string][];groups?:{id:string;title:string}[];periods?:string[];placeholder?:string;dateLabel?:string}) {
  return <section aria-label="Filtros de registros" className="space-y-3 rounded-2xl border bg-white p-4"><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><label className="space-y-1 text-xs font-semibold">Buscar<Input aria-label={placeholder} className="min-h-11" value={list.filters.query} maxLength={300} onChange={e=>list.change('query',e.target.value)} placeholder={placeholder}/></label>{statuses.length>0&&<label className="space-y-1 text-xs font-semibold">Estado<select className={select} value={list.filters.status} onChange={e=>list.change('status',e.target.value)}><option value="">Todos los estados</option>{statuses.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label>}{groups&&<label className="space-y-1 text-xs font-semibold">Grupo<select className={select} value={list.filters.group} onChange={e=>list.change('group',e.target.value)}><option value="">Todos los grupos</option><option value="__none">Sin grupo</option>{groups.map(group=><option key={group.id} value={group.id}>{group.title}</option>)}</select></label>}{periods&&<label className="space-y-1 text-xs font-semibold">Periodo<select className={select} value={list.filters.period} onChange={e=>list.change('period',e.target.value)}><option value="">Todos los periodos</option><option value="__none">Sin periodo registrado</option>{periods.map(period=><option key={period} value={period}>{period}</option>)}</select></label>}<label className="space-y-1 text-xs font-semibold">Desde · {dateLabel}<Input className="min-h-11" type="date" value={list.filters.from} onChange={e=>list.change('from',e.target.value)}/></label><label className="space-y-1 text-xs font-semibold">Hasta · {dateLabel}<Input className="min-h-11" type="date" value={list.filters.to} onChange={e=>list.change('to',e.target.value)}/></label></div>{list.filters.from&&list.filters.to&&list.filters.from>list.filters.to&&<p role="alert" className="text-sm text-red-700">La fecha final debe ser igual o posterior a la inicial.</p>}<div className="flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-slate-500">{list.pagination.total} registro(s) coinciden</p><Button size="sm" variant="outline" onClick={list.reset}>Limpiar filtros</Button></div></section>;
}
export function RecordPager({list}:{list:ListState}) { const p=list.pagination;return <div className="flex flex-wrap items-center justify-between gap-3 rounded-xl border bg-white p-3"><label className="flex items-center gap-2 text-xs font-semibold">Por página<select aria-label="Registros por página" className="min-h-11 rounded-lg border px-2" value={list.size} onChange={e=>list.setSize(Number(e.target.value))}>{[10,20,50].map(size=><option key={size}>{size}</option>)}</select></label><span className="text-xs text-slate-500" aria-live="polite">{p.from}–{p.to} de {p.total} · página {p.page+1} de {p.pages}</span><div className="flex gap-2"><Button variant="outline" disabled={p.page===0} onClick={()=>list.page(p.page-1)}>Anterior</Button><Button variant="outline" disabled={p.page===p.pages-1} onClick={()=>list.page(p.page+1)}>Siguiente</Button></div></div>; }
