"use client";
import { useState } from 'react';
import { ArchiveRestore } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogDescription, DialogTitle, DialogTrigger, DialogFooter } from '@/components/ui/dialog';
type Row={id:string;title:string;status:string;updated_at:string;data:Record<string,unknown>};
export function SubjectRestore({row,count,mutate}:{row:Row;count:number;mutate:(body:Record<string,unknown>,success?:string)=>Promise<boolean>}) {
  const [open,setOpen]=useState(false),[restore,setRestore]=useState(Boolean((row.data.subjectArchive as Record<string,unknown>|undefined)?.operationId));
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><ArchiveRestore/> {row.status==='archived'?'Restaurar':'Recuperar contenidos'}</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{row.status==='archived'?'Restaurar materia':'Recuperar contenidos archivados'}</DialogTitle><DialogDescription>{row.title} · {String(row.data.period)}. La materia conserva su identidad y sus archivos. Revisa el contenido antes de publicarlo.</DialogDescription></DialogHeader><label className="flex items-start gap-3 rounded-xl border p-4 text-sm"><input type="checkbox" checked={restore} onChange={e=>setRestore(e.target.checked)} className="mt-1"/><span><strong>Recuperar {count} contenido(s) archivado(s)</strong><span className="mt-2 block text-slate-600">Materiales y simuladores volverán como borradores; preguntas y bloques quedarán pendientes. Los temas se recuperan si no hay números repetidos.</span></span></label>{!(row.data.subjectArchive as Record<string,unknown>|undefined)?.operationId&&<p className="rounded-xl bg-amber-50 p-3 text-sm leading-6">Este archivo de materia es anterior a la mejora. Si activas la opción, se recuperarán los elementos que sigan archivados en esta materia y periodo.</p>}<p className="text-xs leading-5 text-slate-500">Los exámenes afectados podrán volver a borrador con sus cuotas anteriores si no se editaron después. Los intentos ya realizados se conservan.</p><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancelar</Button><Button onClick={async()=>{if(await mutate({action:'restore_subject',id:row.id,revision:row.data.subjectRevision||row.updated_at,restoreContent:restore},'Materia recuperada. Revisa y publica sus materiales, preguntas y simuladores.'))setOpen(false);}}>Recuperar</Button></DialogFooter></DialogContent></Dialog>;
}
