import { zipSync, strToU8 } from 'fflate';
import { completedReportAttempts, studentReportSummaries } from './reporting.ts';
import { recordTimestamp, type ListFilters } from './record-lists.ts';
type Attempt={id:string;title:string;status:string;created_by:string;created_at:string;group_id?:string|null;data:Record<string,unknown>};
type Student={id:string;role:string;full_name:string;email:string;group_id?:string|null};
type Group={id:string;title:string};
type Cell=string|number;
export type ReportTable={name:string;headers:string[];rows:Cell[][]};
export type ReportDocument={generatedAt:string;filters:string[];tables:ReportTable[]};
function date(value:string){const at=recordTimestamp(value);return Number.isFinite(at)?new Intl.DateTimeFormat('es-EC',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',timeZone:'America/Guayaquil'}).format(at):'Sin fecha';}
export function buildReportDocument(students:Student[],filteredInput:Attempt[],groups:Group[],filters:ListFilters,now=new Date()):ReportDocument{
 const attempts=completedReportAttempts(filteredInput),summaries=studentReportSummaries(students,attempts,filters),group=(id:unknown)=>groups.find(g=>g.id===id)?.title||'Sin grupo';
 return{generatedAt:date(now.toISOString()),filters:[`Búsqueda: ${filters.query||'Todas'}`,`Grupo: ${filters.group==='__none'?'Sin grupo':filters.group?group(filters.group):'Todos'}`,`Estado: ${filters.status==='passed'?'Aprobados':filters.status==='reinforce'?'Necesitan refuerzo':'Todos'}`,`Periodo: ${filters.period==='__none'?'Sin periodo':filters.period||'Todos'}`,`Fechas: ${filters.from||'Sin inicio'} a ${filters.to||'Sin final'}`],
 tables:[{name:'Estudiantes',headers:['Estudiante','Correo','Grupo actual','Intentos','Promedio /20','Mejor nota /20','Última nota /20','Último resultado','Última finalización','Grupo del último intento'],rows:summaries.map(s=>[s.student.full_name,s.student.email,group(s.student.group_id),s.attempts,s.attempts?Math.round(s.average*100)/100:'',s.attempts?s.best:'',s.latest?Number(s.latest.data.score):'',s.latest?s.latest.data.passed?'Aprobado':'Necesita refuerzo':'Sin intentos',s.latest?date(String(s.latest.data.completedAt||s.latest.created_at)):'',s.latest?group(s.latest.group_id):''])},
 {name:'Intentos',headers:['Estudiante','Correo','Grupo del intento','Evaluación','Periodo','Finalización','Nota /20','Correctas','Preguntas','Duración en segundos','Resultado','Identificador'],rows:attempts.map(a=>{const s=students.find(s=>s.id===a.created_by);return[s?.full_name||String(a.data.studentName||'Estudiante'),s?.email||'',group(a.group_id),a.title,String(a.data.period||'Sin periodo'),date(String(a.data.completedAt||a.created_at)),Number(a.data.score),Number(a.data.correct||0),Number(a.data.total||0),Number(a.data.durationSeconds||0),a.data.passed?'Aprobado':'Necesita refuerzo',a.id];})}]};
}
const xml=(value:unknown)=>String(value).replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'","&apos;");
function column(n:number){let out='';for(n++;n;n=Math.floor((n-1)/26))out=String.fromCharCode(65+(n-1)%26)+out;return out;}
export function reportExcel(doc:ReportDocument){
 const tables=[...doc.tables,{name:'Filtros',headers:['Configuración','Valor'],rows:[['Generado (Ecuador)',doc.generatedAt],...doc.filters.map(f=>[f.slice(0,f.indexOf(':')),f.slice(f.indexOf(':')+2)]),['Escala de notas','0 a 20'],['Datos','Intentos finalizados y todos los registros del filtro, sin limitar a la página visible']]}],files:Record<string,Uint8Array>={};
 const prefix='<?xml version="1.0" encoding="UTF-8" standalone="yes"?>';
 files['[Content_Types].xml']=strToU8(prefix+`<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/>${tables.map((_,i)=>`<Override PartName="/xl/worksheets/sheet${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`);
 files['_rels/.rels']=strToU8(prefix+'<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');
 files['xl/workbook.xml']=strToU8(prefix+`<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${tables.map((t,i)=>`<sheet name="${xml(t.name)}" sheetId="${i+1}" r:id="rId${i+1}"/>`).join('')}</sheets></workbook>`);
 files['xl/_rels/workbook.xml.rels']=strToU8(prefix+`<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${tables.map((_,i)=>`<Relationship Id="rId${i+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${i+1}.xml"/>`).join('')}<Relationship Id="rId${tables.length+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>`);
 files['xl/styles.xml']=strToU8(prefix+'<styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><name val="Calibri"/><color rgb="FFFFFFFF"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF003F32"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"><alignment vertical="top" wrapText="1"/></xf><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFont="1" applyFill="1"><alignment wrapText="1" vertical="center"/></xf><xf numFmtId="2" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>');
 tables.forEach((t,i)=>{const rows=[t.headers,...t.rows];files[`xl/worksheets/sheet${i+1}.xml`]=strToU8(prefix+`<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><dimension ref="A1:${column(t.headers.length-1)}${rows.length}"/><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols>${t.headers.map((_,c)=>`<col min="${c+1}" max="${c+1}" width="${c<3?30:23}" customWidth="1"/>`).join('')}</cols><sheetData>${rows.map((r,n)=>`<row r="${n+1}"${n===0?' ht="32" customHeight="1"':''}>${r.map((cell,c)=>typeof cell==='number'&&Number.isFinite(cell)?`<c r="${column(c)}${n+1}" s="${Number.isInteger(cell)?0:2}" t="n"><v>${cell}</v></c>`:`<c r="${column(c)}${n+1}" s="${n===0?1:0}" t="inlineStr"><is><t xml:space="preserve">${xml(cell)}</t></is></c>`).join('')}</row>`).join('')}</sheetData><autoFilter ref="A1:${column(t.headers.length-1)}${rows.length}"/></worksheet>`);});
 return zipSync(files,{level:6});
}
