import { assertActiveAdministrator, PublicError } from './security.ts';
import { removeSubjectFromDistribution, sameSubject } from './subjects.ts';
import { removeSubjectFromBlockDistribution } from './final-exam-blocks.ts';
import { requestKey } from './single-flight.ts';
type Actor={id:string;role:string;status:string};
type Stored={id:string;title:string;status:string;data_json:string;updated_at:string};
const currentPeriodSQL="(EXISTS(SELECT 1 FROM records WHERE kind='period' AND title=? AND json_extract(data_json,'$.current')=1) OR (?='2026-2027' AND NOT EXISTS(SELECT 1 FROM records WHERE kind='period' AND json_extract(data_json,'$.current')=1)))";
const scope="lower(json_extract(data_json,'$.subject'))=lower(?) AND json_extract(data_json,'$.area')=? AND json_extract(data_json,'$.period')=?";
function stamp(row:Pick<Stored,'title'|'status'>,data:Record<string,unknown>){const{subjectRemoval:_subjectRemoval,...config}=data;void _subjectRemoval;return requestKey({title:row.title,status:row.status,data:config});}
export async function removeAcademicSubject(database:D1Database,input:Record<string,unknown>,period:string,actor:Actor){
  assertActiveAdministrator(actor.role,actor.status);
  const area=String(input.area||''),subject=typeof input.subject==='string'?input.subject.trim():'',requested=String(input.period||period);
  if(!['complexive','final_degree'].includes(area)||!subject||subject.length>180||['general','23 materias'].includes(subject.toLowerCase()))throw new PublicError('Selecciona una materia válida.');
  if(requested!==period)throw new PublicError('Gestiona materias del periodo vigente; el histórico se conserva.',409);
  const existing=await database.prepare("SELECT id,title,status,data_json,updated_at FROM records WHERE kind='subject' AND lower(title)=lower(?) AND json_extract(data_json,'$.area')=? AND json_extract(data_json,'$.period')=? LIMIT 1").bind(subject,area,period).first<Stored>();
  if(existing?.status==='archived')return{id:existing.id,archivedContent:0,adjustedFinals:0,alreadyRemoved:true};
  const id=existing?.id||`subject_${crypto.randomUUID()}`,operationId=crypto.randomUUID(),removedAt=new Date().toISOString(),revision=crypto.randomUUID(),data={...(existing?JSON.parse(existing.data_json):{area,period}),subjectArchive:{operationId,removedAt,actorId:actor.id},subjectRevision:revision};
  const catalog=existing?database.prepare(`UPDATE records SET status='archived',data_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND kind='subject' AND status=? AND data_json=? AND ${currentPeriodSQL}`).bind(JSON.stringify(data),id,existing.status,existing.data_json,period,period):database.prepare(`INSERT INTO records(id,kind,title,status,data_json,created_by) SELECT ?,'subject',?,'archived',?,? WHERE NOT EXISTS(SELECT 1 FROM records WHERE kind='subject' AND lower(title)=lower(?) AND json_extract(data_json,'$.area')=? AND json_extract(data_json,'$.period')=?) AND ${currentPeriodSQL}`).bind(id,subject,JSON.stringify(data),actor.id,subject,area,period,period,period);
  const guard="EXISTS(SELECT 1 FROM records WHERE id=? AND kind='subject' AND status='archived' AND json_extract(data_json,'$.subjectArchive.operationId')=?)";
  const statements=[catalog,database.prepare(`UPDATE records SET data_json=json_set(data_json,'$.subjectArchive',json_object('operationId',?,'removedAt',?,'previousStatus',status)),status='archived',updated_at=CURRENT_TIMESTAMP WHERE kind IN ('resource','question','simulator','question_block','topic') AND status!='archived' AND ${scope} AND ${guard}`).bind(operationId,removedAt,subject,area,period,id,operationId)];
  const finals=(await database.prepare("SELECT id,title,status,data_json,updated_at FROM records WHERE kind='simulator' AND status!='archived' AND json_extract(data_json,'$.area')=? AND json_extract(data_json,'$.period')=?").bind(area,period).all<Stored>()).results;
  for(const row of finals){const original=JSON.parse(row.data_json) as Record<string,unknown>;if(sameSubject(original.subject,subject))continue;const next={...original};let status='draft';if(next.selectionMode==='blocks'){const adjusted=removeSubjectFromBlockDistribution(next.blockDistribution,subject);if(adjusted.entries.length===(Array.isArray(next.blockDistribution)?next.blockDistribution.length:0))continue;Object.assign(next,{blockDistribution:adjusted.entries,count:adjusted.count});if(!adjusted.entries.length)status='archived';}else{const adjusted=removeSubjectFromDistribution(next.distribution,subject);if(!adjusted.changed)continue;Object.assign(next,{distribution:adjusted.distribution,count:adjusted.count});if(!adjusted.distribution.length)status='archived';}
    const history=Array.isArray(original.subjectRemovalHistory)?original.subjectRemovalHistory:[];if(history.length>=100)throw new PublicError('Un examen alcanzó 100 cambios de materias. Conserva su historial antes de cambiarlo.',409);
    const previous={distribution:original.distribution||[],blockDistribution:original.blockDistribution||[],count:original.count};Object.assign(next,{subjectRemovalHistory:[...history,{operationId,subject,removedAt,previous}],subjectRemoval:{operationId,subject,previous}});(next.subjectRemoval as Record<string,unknown>).after=stamp({title:row.title,status},next);
    statements.push(database.prepare(`UPDATE records SET status=?,data_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND kind='simulator' AND status=? AND data_json=? AND ${guard}`).bind(status,JSON.stringify(next),row.id,row.status,row.data_json,id,operationId));
  }
  const results=await database.batch(statements);if(results[0].meta.changes!==1)throw new PublicError('La materia cambió mientras la quitabas. Actualiza y vuelve a intentar.',409);
  return{id,archivedContent:Number(results[1].meta.changes||0),adjustedFinals:results.slice(2).reduce((sum,row)=>sum+Number(row.meta.changes||0),0)};
}
export async function restoreAcademicSubject(database:D1Database,input:Record<string,unknown>,period:string,actor:Actor){
  assertActiveAdministrator(actor.role,actor.status);
  const row=await database.prepare("SELECT id,title,status,data_json,updated_at FROM records WHERE id=? AND kind='subject'").bind(input.id).first<Stored>();if(!row)throw new PublicError('Materia no encontrada.',404);
  const old=JSON.parse(row.data_json) as Record<string,unknown>,area=String(old.area),meta=old.subjectArchive as Record<string,unknown>|undefined;
  if(old.period!==period||!['complexive','final_degree'].includes(area)||!['archived','published'].includes(row.status))throw new PublicError('Restaura materias del periodo vigente.',409);
  if(input.revision!==(old.subjectRevision||row.updated_at))throw new PublicError('La materia cambió. Actualiza antes de restaurar.',409);
  if(typeof input.restoreContent!=='boolean')throw new PublicError('Indica si deseas recuperar los contenidos.');
  const operation=String(meta?.operationId||''),restoredAt=new Date().toISOString(),revision=crypto.randomUUID(),next={...old,subjectRevision:revision,subjectArchive:{...meta,restoredAt}};
  const eligible="(?='' OR (json_extract(data_json,'$.subjectArchive.operationId')=? AND json_extract(data_json,'$.subjectArchive.restoredAt') IS NULL))",values=[row.title,area,period,operation,operation];
  // A recovered topic cannot collide with a topic created after a catalog-only recovery.
  const conflict="EXISTS(SELECT 1 FROM records AS retired WHERE retired.kind='topic' AND retired.status='archived' AND lower(json_extract(retired.data_json,'$.subject'))=lower(?) AND json_extract(retired.data_json,'$.area')=? AND json_extract(retired.data_json,'$.period')=? AND (?='' OR (json_extract(retired.data_json,'$.subjectArchive.operationId')=? AND json_extract(retired.data_json,'$.subjectArchive.restoredAt') IS NULL)) AND EXISTS(SELECT 1 FROM records AS active WHERE active.kind='topic' AND active.status='published' AND json_extract(active.data_json,'$.area')=json_extract(retired.data_json,'$.area') AND json_extract(active.data_json,'$.period')=json_extract(retired.data_json,'$.period') AND lower(json_extract(active.data_json,'$.subject'))=lower(json_extract(retired.data_json,'$.subject')) AND (active.title=retired.title OR json_extract(active.data_json,'$.number')=json_extract(retired.data_json,'$.number'))))";
  if(input.restoreContent&&await database.prepare(`SELECT 1 AS conflict WHERE ${conflict}`).bind(...values).first())throw new PublicError('Un tema archivado coincide con un tema activo. Ajusta su número o nombre en Gestionar temas antes de recuperar los contenidos.',409);
  const catalogGuard=input.restoreContent?` AND NOT ${conflict}`:'';
  const statements=[database.prepare(`UPDATE records SET status='published',data_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND kind='subject' AND status=? AND data_json=? AND NOT EXISTS(SELECT 1 FROM records AS other WHERE other.kind='subject' AND other.status='published' AND other.id!=? AND lower(other.title)=lower(?) AND json_extract(other.data_json,'$.area')=? AND json_extract(other.data_json,'$.period')=?) AND ${currentPeriodSQL}${catalogGuard}`).bind(JSON.stringify(next),row.id,row.status,row.data_json,row.id,row.title,area,period,period,period,...(input.restoreContent?values:[]))];
  const guard="EXISTS(SELECT 1 FROM records WHERE id=? AND kind='subject' AND status='published' AND json_extract(data_json,'$.subjectRevision')=?)";
  if(input.restoreContent){statements.push(database.prepare(`UPDATE records SET status=CASE kind WHEN 'question' THEN 'pending' WHEN 'question_block' THEN 'pending' WHEN 'topic' THEN 'published' ELSE 'draft' END,data_json=json_set(data_json,'$.subjectArchive.restoredAt',?),updated_at=CURRENT_TIMESTAMP WHERE kind IN ('resource','question','question_block','topic','simulator') AND status='archived' AND ${scope} AND ${eligible} AND ${guard}`).bind(restoredAt,...values,row.id,revision));
    if(operation){const finals=(await database.prepare("SELECT id,title,status,data_json,updated_at FROM records WHERE kind='simulator' AND status IN ('draft','archived') AND json_extract(data_json,'$.area')=? AND json_extract(data_json,'$.period')=? AND json_extract(data_json,'$.subjectRemoval.operationId')=?").bind(area,period,operation).all<Stored>()).results;
      for(const final of finals){const data=JSON.parse(final.data_json) as Record<string,unknown>,removal=data.subjectRemoval as Record<string,unknown>;if(removal.after!==stamp(final,data))continue;const previous=removal.previous as Record<string,unknown>;const recovered={...data,...previous,subjectRemoval:{...removal,restoredAt}};statements.push(database.prepare(`UPDATE records SET status='draft',data_json=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND kind='simulator' AND status=? AND data_json=? AND ${guard}`).bind(JSON.stringify(recovered),final.id,final.status,final.data_json,row.id,revision));}
    }
  }
  const results=await database.batch(statements);if(results[0].meta.changes!==1)throw new PublicError('La materia o sus temas cambiaron. Actualiza antes de recuperar.',409);
  return{id:row.id,restoredContent:Number(results[1]?.meta.changes||0),restoredFinals:results.slice(2).reduce((sum,result)=>sum+Number(result.meta.changes||0),0)};
}
